// Code generated by jay on Wed, 27 May 2026 09:02:17 +0800, DO NOT EDIT.
// -go:generate faker-jay -vc  -o cparser_.tmp cparser.y < skeleton.cs 2>NUL

package cxxParser_test

import "testing"

//region --- ValueTests ---

// ============================================================================
// ValueTests — from ValueTests.cs
// ============================================================================

//endregion

//region --- WhileTests ---

// ============================================================================
// WhileTests — from WhileTests.cs
// ============================================================================

func Test_WhileTests_InnerForLoop(t *testing.T) {
	safeRun(t, `
void main()
{
	int s = 0;
    int a = 0;
	
	while (s < 3)
	{
		for (int pos = 5; pos < 7; pos++)
		{
            a++;
		}
		s++;
	}
    assertAreEqual(6, a);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- GettingStartedTests ---

// ============================================================================
// GettingStartedTests — from GettingStartedTests.cs
// ============================================================================

//endregion

//region --- CastTests ---

// ============================================================================
// CastTests — from CastTests.cs
// ============================================================================

func Test_CastTests_CharMasksInt(t *testing.T) {
	safeRun(t, `
void main () {
    assertAreEqual (' ', (char)0x2020);
}
	`, newArduinoTestMachineInfo(t))
}

//endregion

//region --- TypedefTests ---

// ============================================================================
// TypedefTests — from TypedefTests.cs
// ============================================================================

func Test_TypedefTests_GlobalInt(t *testing.T) {
	safeRun(t, `
typedef int Foo;
Foo one = 1;
void main () {
    assertAreEqual (1, one);
}
	`, newTestMachineInfo(t))
}

func Test_TypedefTests_LocalInt(t *testing.T) {
	safeRun(t, `
typedef int Foo;
void main () {
    Foo one = 1;
    assertAreEqual (1, one);
}
	`, newTestMachineInfo(t))
}

func Test_TypedefTests_ForInt(t *testing.T) {
	safeRun(t, `
typedef int Foo;
void main () {
    int n = 0;
    for (Foo one = 0; one < 10; one++) {
        n++;
    }
    assertAreEqual (10, n);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- AssignTests ---

// ============================================================================
// AssignTests — from AssignTests.cs
// ============================================================================

func Test_AssignTests_GlobalAssignBits(t *testing.T) {
	safeRun(t, `
int x = 0;
void main() {
    x |= 0xCC;
    x &= 0xF0;
    x ^= 0xFF;
    assertAreEqual(63, x);
}
	`, newTestMachineInfo(t))
}

func Test_AssignTests_GlobalAssignDoubles(t *testing.T) {
	safeRun(t, `
double x = 0.0;
void main() {
    x += 100;
    x -= 50;
    x /= 10;
    x *= 1000000.0;
    assertDoublesAreEqual(5000000.0, x);
}
	`, newTestMachineInfo(t))
}

func Test_AssignTests_GlobalAssignLogic(t *testing.T) {
	safeRun(t, `
bool x = false;
void main() {
    x ||= true;
    x &&= true;
    assertBoolsAreEqual(true, x);
}
	`, newTestMachineInfo(t))
}

func Test_AssignTests_GlobalAssign(t *testing.T) {
	safeRun(t, `
int x = 0;
void main() {
    x = 1234;
    assertAreEqual(1234, x);
}
	`, newTestMachineInfo(t))
}

func Test_AssignTests_GlobalAfterArray(t *testing.T) {
	safeRun(t, `
int a[] = {111, 222};
int x = 0;
void main() {
    x = 1234;
    int i = 0;
    for (i = 0; i < 10; i++) {
    }
    assertAreEqual(1234, x);
    assertAreEqual(10, i);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- EnumTests ---

// ============================================================================
// EnumTests — from EnumTests.cs
// ============================================================================

func Test_EnumTests_NamedUnnumbered(t *testing.T) {
	safeRun(t, `
enum Numbers { ZERO, ONE, TWO };
void main() {
    assertAreEqual(0, ZERO);
    assertAreEqual(1, ONE);
    assertAreEqual(2, TWO);
}
	`, newTestMachineInfo(t))
}

func Test_EnumTests_NamedNumbered(t *testing.T) {
	safeRun(t, `
enum Numbers { ONE = 1, ZERO = 0, H = 100, X, Y = 1000, Z };
void main() {
    assertAreEqual(1, ONE);
    assertAreEqual(0, ZERO);
    assertAreEqual(100, H);
    assertAreEqual(101, X);
    assertAreEqual(1000, Y);
    assertAreEqual(1001, Z);
}
	`, newTestMachineInfo(t))
}

func Test_EnumTests_UnnamedNumbered(t *testing.T) {
	safeRun(t, `
enum { ONE = 1, ZERO = 0, H = 100, X, Y = -1000, Z, V25 = 2 * 10 + 5 };
void main() {
    assertAreEqual(1, ONE);
    assertAreEqual(0, ZERO);
    assertAreEqual(100, H);
    assertAreEqual(101, X);
    assertAreEqual(-1000, Y);
    assertAreEqual(-999, Z);
    assertAreEqual(25, V25);
}
	`, newTestMachineInfo(t))
}

func Test_EnumTests_UnnamedRecursive(t *testing.T) {
	safeRun(t, `
enum { ZERO, ONE, OTHER_ONE = ONE, THREE = 2 + OTHER_ONE };
void main() {
    assertAreEqual(1, ONE);
    assertAreEqual(OTHER_ONE, OTHER_ONE);
    assertAreEqual(3, THREE);
}
	`, newTestMachineInfo(t))
}

func Test_EnumTests_GlobalInit(t *testing.T) {
	safeRun(t, `
enum Numbers { ZERO, ONE };
enum Numbers one = ONE;
void main() {
    assertAreEqual(1, one);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- StructReturnTests ---

// ============================================================================
// StructReturnTests — from StructReturnTests.cs
// ============================================================================

func Test_StructReturnTests_ReturnStructByValue(t *testing.T) {
	safeRun(t, `
struct Point { int x; int y; };
Point make(int x, int y) {
    Point p;
    p.x = x;
    p.y = y;
    return p;
}
void main() {
    Point p = make(3, 4);
    assertAreEqual(3, p.x);
    assertAreEqual(4, p.y);
}
	`, newTestMachineInfo(t))
}

func Test_StructReturnTests_ReturnStructFromNestedCall(t *testing.T) {
	safeRun(t, `
struct Point { int x; int y; };
Point make(int x, int y) {
    Point p;
    p.x = x;
    p.y = y;
    return p;
}
Point add(Point a, Point b) {
    Point r;
    r.x = a.x + b.x;
    r.y = a.y + b.y;
    return r;
}
void main() {
    Point p = add(make(1, 2), make(3, 4));
    assertAreEqual(4, p.x);
    assertAreEqual(6, p.y);
}
	`, newTestMachineInfo(t))
}

func Test_StructReturnTests_ChainedStructReturn(t *testing.T) {
	safeRun(t, `
struct V { int x; };
V make(int x) { V v; v.x = x; return v; }
V add(V a, V b) { V r; r.x = a.x + b.x; return r; }
void main() {
    V result = add(add(make(1), make(2)), make(3));
    assertAreEqual(6, result.x);
}
	`, newTestMachineInfo(t))
}

func Test_StructReturnTests_AccessFieldOfReturnedStruct(t *testing.T) {
	safeRun(t, `
struct Point { int x; int y; };
Point make(int x, int y) {
    Point p;
    p.x = x;
    p.y = y;
    return p;
}
void main() {
    int x = make(5, 10).x;
    assertAreEqual(5, x);
}
	`, newTestMachineInfo(t))
}

func Test_StructReturnTests_ReturnStructWithSingleField(t *testing.T) {
	safeRun(t, `
struct Wrapper { int value; };
Wrapper wrap(int v) { Wrapper w; w.value = v; return w; }
void main() {
    Wrapper w = wrap(42);
    assertAreEqual(42, w.value);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- GotoTests ---

// ============================================================================
// GotoTests — from GotoTests.cs
// ============================================================================

func Test_GotoTests_ForwardGoto(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 0;
    goto skip;
    x = 42;
skip:
    assertAreEqual(0, x);
}
	`, newTestMachineInfo(t))
}

func Test_GotoTests_BackwardGoto(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 0;
loop:
    x = x + 1;
    if (x < 5)
        goto loop;
    assertAreEqual(5, x);
}
	`, newTestMachineInfo(t))
}

func Test_GotoTests_GotoSkipsMultipleStatements(t *testing.T) {
	safeRun(t, `
void main()
{
    int a = 1;
    goto end;
    a = 2;
    a = 3;
    a = 4;
end:
    assertAreEqual(1, a);
}
	`, newTestMachineInfo(t))
}

func Test_GotoTests_MultipleLabels(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 0;
    goto second;
first:
    x = x + 10;
    goto done;
second:
    x = x + 1;
    goto first;
done:
    assertAreEqual(11, x);
}
	`, newTestMachineInfo(t))
}

func Test_GotoTests_GotoWithinNestedBlocks(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 0;
    if (1) {
        goto skip;
    }
    x = 42;
skip:
    assertAreEqual(0, x);
}
	`, newTestMachineInfo(t))
}

func Test_GotoTests_LabelBeforeReturn(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 1;
    goto end;
    x = 2;
end:
    return;
}
	`, newTestMachineInfo(t))
}

func Test_GotoTests_GotoInLoopBreakout(t *testing.T) {
	safeRun(t, `
void main()
{
    int sum = 0;
    int i = 0;
    while (i < 100) {
        sum = sum + i;
        i = i + 1;
        if (i == 5)
            goto done;
    }
done:
    assertAreEqual(10, sum);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- SwitchTests ---

// ============================================================================
// SwitchTests — from SwitchTests.cs
// ============================================================================

func Test_SwitchTests_EmptySwitch(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 6;
	switch (x)
	{
	}
    assertAreEqual(6, x);
}
	`, newTestMachineInfo(t))
}

func Test_SwitchTests_OnlyDefault(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 6;
	switch (x)
	{
        default:
            x = 1000;
	}
    assertAreEqual(1000, x);
}
	`, newTestMachineInfo(t))
}

func Test_SwitchTests_OnlyDefaultBreak(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 6;
	switch (x)
	{
        default:
            break;
            x = 1000;
	}
    assertAreEqual(6, x);
}
	`, newTestMachineInfo(t))
}

func Test_SwitchTests_HitOnly(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 6;
	switch (x)
	{
        case 1:
            x = 100;
            break;
        case 6:
            x = 600;
            break;
        default:
            x = 1000;
	}
    assertAreEqual(600, x);
}
	`, newTestMachineInfo(t))
}

func Test_SwitchTests_HitDefault(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 5;
	switch (x)
	{
        default:
            x = 1000;
            break;
        case 1:
            x = 100;
            break;
        case 6:
            x = 600;
            break;
	}
    assertAreEqual(1000, x);
}
	`, newTestMachineInfo(t))
}

func Test_SwitchTests_NoDefault(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 6;
	switch (x)
	{
        case 1:
            x = 100;
            break;
        case 5:
            x = 500;
            break;
	}
    assertAreEqual(6, x);
}
	`, newTestMachineInfo(t))
}

func Test_SwitchTests_Fallthrough(t *testing.T) {
	safeRun(t, `
void main()
{
    int x = 5;
    switch (x)
    {
        case 1:
            x = 100;
            break;
        case 5:
            x = 500;
        case 6:
            x = 600;
            break;
    }
    assertAreEqual(600, x);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- ReferenceTests ---

// ============================================================================
// ReferenceTests — from ReferenceTests.cs
// ============================================================================

func Test_ReferenceTests_PassByReference(t *testing.T) {
	safeRun(t, `
void inc(int& x) { x = x + 1; }
void main() {
    int a = 10;
    inc(a);
    assertAreEqual(11, a);
}
	`, newTestMachineInfo(t))
}

func Test_ReferenceTests_PassStructByConstReference(t *testing.T) {
	safeRun(t, `
struct S { int a; int b; };
int sum(const S& s) { return s.a + s.b; }
void main() {
    S s;
    s.a = 3;
    s.b = 4;
    assertAreEqual(7, sum(s));
}
	`, newTestMachineInfo(t))
}

func Test_ReferenceTests_ReferenceDoesNotCopyStruct(t *testing.T) {
	safeRun(t, `
struct S { int x; };
void modify(S& s) { s.x = 42; }
void main() {
    S s;
    s.x = 0;
    modify(s);
    assertAreEqual(42, s.x);
}
	`, newTestMachineInfo(t))
}

func Test_ReferenceTests_ConstRefAcceptsRvalue(t *testing.T) {
	safeRun(t, `
int identity(const int& x) { return x; }
void main() {
    assertAreEqual(42, identity(42));
}
	`, newTestMachineInfo(t))
}

func Test_ReferenceTests_ReferenceModifiesCallerVariable(t *testing.T) {
	safeRun(t, `
void swap(int& a, int& b) {
    int temp = a;
    a = b;
    b = temp;
}
void main() {
    int x = 1;
    int y = 2;
    swap(x, y);
    assertAreEqual(2, x);
    assertAreEqual(1, y);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- ArrayTests ---

// ============================================================================
// ArrayTests — from ArrayTests.cs
// ============================================================================

func Test_ArrayTests_GlobalInitInts(t *testing.T) {
	safeRun(t, `
int a[] = { 0, 100, 200, 300, };
void main () {
    assertAreEqual (0, a[0]);
    assertAreEqual (100, a[1]);
    assertAreEqual (200, a[2]);
    assertAreEqual (300, a[3]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_ArrayTests_GlobalInitFloatsToInts(t *testing.T) {
	safeRun(t, `
int a[2] = { 2.0f, 3.0f };
void main () {
    assertAreEqual (2, a[0]);
    assertAreEqual (3, a[1]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_ArrayTests_LocalInitFloatsToInts(t *testing.T) {
	safeRun(t, `
void main () {
    int a[2] = { 2.0f, 3.0f };
    assertAreEqual (2, a[0]);
    assertAreEqual (3, a[1]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_ArrayTests_LocalInitDoublesToInts(t *testing.T) {
	safeRun(t, `
void main () {
    int a[3] = { 1.5, 2.9, 3.1 };
    assertAreEqual (1, a[0]);
    assertAreEqual (2, a[1]);
    assertAreEqual (3, a[2]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_ArrayTests_GlobalInitMultidimensional(t *testing.T) {
	safeRun(t, `
int a[2][3] = { {1, 2, 3}, {4, 5, 6} };
void main () {
    assertAreEqual (1, a[0][0]);
    assertAreEqual (2, a[0][1]);
    assertAreEqual (3, a[0][2]);
    assertAreEqual (4, a[1][0]);
    assertAreEqual (5, a[1][1]);
    assertAreEqual (6, a[1][2]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_ArrayTests_LocalInitMultidimensional(t *testing.T) {
	safeRun(t, `
void main () {
    int a[2][3] = { {10, 20, 30}, {40, 50, 60} };
    assertAreEqual (10, a[0][0]);
    assertAreEqual (20, a[0][1]);
    assertAreEqual (30, a[0][2]);
    assertAreEqual (40, a[1][0]);
    assertAreEqual (50, a[1][1]);
    assertAreEqual (60, a[1][2]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_ArrayTests_LocalInitIntsToFloats(t *testing.T) {
	safeRun(t, `
void main () {
    float a[2] = { 1, 2 };
    assertFloatsAreEqual (1.0f, a[0]);
    assertFloatsAreEqual (2.0f, a[1]);
}
	`, newArduinoTestMachineInfo(t))
}

//endregion

//region --- FloatTests ---

// ============================================================================
// FloatTests — from FloatTests.cs
// ============================================================================

func Test_FloatTests_LargeIntegerConstantToDouble(t *testing.T) {
	safeRun(t, `
double f(double x) { return 10.0 * x; }
void main () {
    assertDoublesAreEqual (2400000.0, f(240000));
}
	`, newArduinoTestMachineInfo(t))
}

func Test_FloatTests_IntegerConstantToDoubleParam(t *testing.T) {
	safeRun(t, `
double f(double x) { return x; }
void main () {
    assertDoublesAreEqual (240000.0, f(240000));
}
	`, newArduinoTestMachineInfo(t))
}

//endregion

//region --- SizeTests ---

// ============================================================================
// SizeTests — from SizeTests.cs
// ============================================================================

//endregion

//region --- ClassTests ---

// ============================================================================
// ClassTests — from ClassTests.cs
// ============================================================================

func Test_ClassTests_EmptyClass(t *testing.T) {
	safeRun(t, `
class C {
};
C c;
void main() {
    assertAreEqual(0, sizeof(c));
    assertAreEqual(0, sizeof(C));
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_TypdefClass(t *testing.T) {
	safeRun(t, `
typedef class C {
    int x;
} OtherC;
OtherC c;
void main() {
    assertAreEqual(4, sizeof(c));
    assertAreEqual(4, sizeof(OtherC));
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_Visibility(t *testing.T) {
	safeRun(t, `
class C {
    int x;
public:
    int y;
};
C c;
void main() {
    int z = c.y;
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_FieldReadAndWrite(t *testing.T) {
	safeRun(t, `
class C {
public:
    int x;
    int y;
};
C c;
void main() {
    c.x = 42;
    c.y = 1000;
    int z = c.x + c.y + 5000;
    assertAreEqual(42, c.x);
    assertAreEqual(1000, c.y);
    assertAreEqual(6042, z);
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_LocalFieldReadAndWrite(t *testing.T) {
	safeRun(t, `
class C {
public:
    int x;
    int y;
};
void main() {
    C c;
    c.x = 42;
    c.y = 1000;
    int z = c.x + c.y + 5000;
    assertAreEqual(42, c.x);
    assertAreEqual(1000, c.y);
    assertAreEqual(6042, z);
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_GlobalConstructor(t *testing.T) {
	safeRun(t, `
class C {
public:
    int x;
    C(int x);
};
C::C(int x) { this->x = x; }
C c(42);
void main() {
    assertAreEqual(42, c.x);
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_LocalConstructor(t *testing.T) {
	safeRun(t, `
class C {
public:
    int x;
    C(int x);
};
C::C(int x) { this->x = x; }
void main() {
    C c(42);
    C c2(-1);
    assertAreEqual(42, c.x);
    assertAreEqual(-1, c2.x);
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_LocalDestructor(t *testing.T) {
	safeRun(t, `
class C {
    int x;
public:
    ~C();
};
C::~C() { this->x = 0; }
void main() {
    C c;
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_InlineMethodDefinitions(t *testing.T) {
	safeRun(t, `
class C {
    int x;
public:
    void setX(int newX) { this->x = newX; }
    int getX() { return this->x; }
};
void main() {
    C c;
    c.setX(101);
    assertAreEqual(101, c.getX());
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_ParseExternalMethodDeclarations(t *testing.T) {
	_ = safeRunParse(t, `
class C {
    int x;
public:
    void setX(int newX);
    int getX();
};
	`)
}

func Test_ClassTests_ExternalMethodDefinitions(t *testing.T) {
	safeRun(t, `
class C {
    int x;
public:
    void setX(int newX);
    int getX();
};
void C::setX(int x) { this->x = x; }
int C::getX() { return this->x; }
void main() {
    C c;
    c.setX(101);
    assertAreEqual(101, c.getX());
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_InlineInstanceMethodCallsOtherInstanceMethod(t *testing.T) {
	safeRun(t, `
class Vec {
    int x;
    int y;
public:
    void set(int ax, int ay) { this->x = ax; this->y = ay; }
    int getX() { return this->x; }
    int getY() { return this->y; }
    int sum() { return this->getX() + this->getY(); }
};
void main() {
    Vec v;
    v.set(3, 4);
    assertAreEqual(7, v.sum());
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_InlineStaticMethodDefinition(t *testing.T) {
	safeRun(t, `
class MathHelper {
public:
    static int add(int a, int b) { return a + b; }
    static int square(int x) { return x * x; }
};
void main() {
    assertAreEqual(7, MathHelper::add(3, 4));
    assertAreEqual(25, MathHelper::square(5));
}
	`, newTestMachineInfo(t))
}

func Test_ClassTests_InlineStructMethodDefinition(t *testing.T) {
	safeRun(t, `
struct Point {
    int x;
    int y;
    void set(int ax, int ay) { this->x = ax; this->y = ay; }
    int getX() { return this->x; }
    int getY() { return this->y; }
};
void main() {
    Point p;
    p.set(10, 20);
    assertAreEqual(10, p.getX());
    assertAreEqual(20, p.getY());
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- StringTests ---

// ============================================================================
// StringTests — from StringTests.cs
// ============================================================================

func Test_StringTests_SingleChar(t *testing.T) {
	safeRun(t, `
char f = 'f';
void main () {
    assertAreEqual ('f', f);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_NullTerminated(t *testing.T) {
	safeRun(t, `
char *bar = "bar";
void main () {
    assertAreEqual ('b', bar[0]);
    assertAreEqual ('a', bar[1]);
    assertAreEqual ('r', bar[2]);
    assertAreEqual (0, bar[3]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_NullTerminatedEmpty(t *testing.T) {
	safeRun(t, `
char *bar = "";
void main () {
    assertAreEqual (0, bar[0]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_Newline(t *testing.T) {
	safeRun(t, `
char *bar = "b\nr";
void main () {
    assertAreEqual ('b', bar[0]);
    assertAreEqual ('\n', bar[1]);
    assertAreEqual ('r', bar[2]);
    assertAreEqual (0, bar[3]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_NullCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\0';
    assertAreEqual (0, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_NullEscapeInString(t *testing.T) {
	safeRun(t, `
char *bar = "ab\0cd";
void main () {
    assertAreEqual ('a', bar[0]);
    assertAreEqual ('b', bar[1]);
    assertAreEqual (0, bar[2]);
    assertAreEqual ('c', bar[3]);
    assertAreEqual ('d', bar[4]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_Multiline(t *testing.T) {
	safeRun(t, `
char *bar = "a\
b\   
c";
void main () {
    assertAreEqual ('a', bar[0]);
    assertAreEqual ('b', bar[1]);
    assertAreEqual ('c', bar[2]);
    assertAreEqual (0, bar[3]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_EscapedSingleQuoteCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\'';
    assertAreEqual (39, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_HexEscapeCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\x41';
    assertAreEqual (65, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_HexEscapeLowercaseCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\x61';
    assertAreEqual (97, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_HexEscapeSingleDigitCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\xA';
    assertAreEqual (10, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_HexEscapeInString(t *testing.T) {
	safeRun(t, `
char *bar = "a\x42z";
void main () {
    assertAreEqual ('a', bar[0]);
    assertAreEqual ('B', bar[1]);
    assertAreEqual ('z', bar[2]);
    assertAreEqual (0, bar[3]);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_BackslashCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\\';
    assertAreEqual (92, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_TabCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\t';
    assertAreEqual (9, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_CarriageReturnCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\r';
    assertAreEqual (13, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_NewlineCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\n';
    assertAreEqual (10, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_HexEscapeZeroCharLiteral(t *testing.T) {
	safeRun(t, `
void main () {
    char c = '\x00';
    assertAreEqual (0, c);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_StringTests_AllEscapesInOneFunction(t *testing.T) {
	safeRun(t, `
void main () {
    assertAreEqual (0, '\0');
    assertAreEqual (39, '\'');
    assertAreEqual (92, '\\');
    assertAreEqual (10, '\n');
    assertAreEqual (13, '\r');
    assertAreEqual (9, '\t');
    assertAreEqual (17, '\x11');
    assertAreEqual (255, '\xFF');
}
	`, newArduinoTestMachineInfo(t))
}

//endregion

//region --- CompilerTests ---

// ============================================================================
// CompilerTests — from CompilerTests.cs
// ============================================================================

func Test_CompilerTests_VoidReturnInVoidFunction(t *testing.T) {
	_ = safeRunCompile(t, `
void foo() { return; } void main() { foo(); }
	`, newTestMachineInfo(t))
}

func Test_CompilerTests_VoidReturnInVoidFunctionWithCode(t *testing.T) {
	_ = safeRunCompile(t, `
int x = 0; void foo() { x = 42; return; x = 99; } void main() { foo(); }
	`, newTestMachineInfo(t))
}

func Test_CompilerTests_NoErrorOnVariableShadowingNestedScope(t *testing.T) {
	_ = safeRunCompile(t, `
void f () { int x = 1; { int x = 2; } }
	`, newTestMachineInfo(t))
}

func Test_CompilerTests_NoErrorOnDistinctVariablesSameScope(t *testing.T) {
	_ = safeRunCompile(t, `
void f () { int x = 1; int y = 2; }
	`, newTestMachineInfo(t))
}

//endregion

//region --- ColorizeTests ---

// ============================================================================
// ColorizeTests — from ColorizeTests.cs
// ============================================================================

//endregion

//region --- LogicTests ---

// ============================================================================
// LogicTests — from LogicTests.cs
// ============================================================================

func Test_LogicTests_AndWithFunctionCalls(t *testing.T) {
	safeRun(t, `
bool returnsFalse () { return false; }
bool returnsTrue () { return true; }
void main () {
    assertBoolsAreEqual (false, returnsFalse() && returnsTrue());
    assertBoolsAreEqual (false, returnsTrue() && returnsFalse());
    assertBoolsAreEqual (true, returnsTrue() && returnsTrue());
    assertBoolsAreEqual (false, returnsFalse() && returnsFalse());
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_OrWithFunctionCalls(t *testing.T) {
	safeRun(t, `
bool returnsFalse () { return false; }
bool returnsTrue () { return true; }
void main () {
    assertBoolsAreEqual (true, returnsFalse() || returnsTrue());
    assertBoolsAreEqual (true, returnsTrue() || returnsFalse());
    assertBoolsAreEqual (true, returnsTrue() || returnsTrue());
    assertBoolsAreEqual (false, returnsFalse() || returnsFalse());
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_AndShortCircuitPreventsRightSideEffects(t *testing.T) {
	safeRun(t, `
int x = 0;
void sideEffect () { x = 1; }
bool returnsFalse () { return false; }
void main () {
    bool result = returnsFalse() && (sideEffect(), true);
    assertBoolsAreEqual (false, result);
    assertAreEqual (0, x);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_AndNoShortCircuitExecutesRightSide(t *testing.T) {
	safeRun(t, `
int x = 0;
void sideEffect () { x = 1; }
bool returnsTrue () { return true; }
void main () {
    bool result = returnsTrue() && (sideEffect(), true);
    assertBoolsAreEqual (true, result);
    assertAreEqual (1, x);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_OrShortCircuitPreventsRightSideEffects(t *testing.T) {
	safeRun(t, `
int x = 0;
void sideEffect () { x = 1; }
bool returnsTrue () { return true; }
void main () {
    bool result = returnsTrue() || (sideEffect(), true);
    assertBoolsAreEqual (true, result);
    assertAreEqual (0, x);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_OrNoShortCircuitExecutesRightSide(t *testing.T) {
	safeRun(t, `
int x = 0;
void sideEffect () { x = 1; }
bool returnsFalse () { return false; }
void main () {
    bool result = returnsFalse() || (sideEffect(), true);
    assertBoolsAreEqual (true, result);
    assertAreEqual (1, x);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_NestedAndOr(t *testing.T) {
	safeRun(t, `
bool returnsFalse () { return false; }
bool returnsTrue () { return true; }
void main () {
    assertBoolsAreEqual (true, returnsTrue() && returnsTrue() && returnsTrue());
    assertBoolsAreEqual (false, returnsTrue() && returnsFalse() && returnsTrue());
    assertBoolsAreEqual (false, returnsFalse() && returnsTrue() && returnsTrue());
    assertBoolsAreEqual (true, returnsFalse() || returnsFalse() || returnsTrue());
    assertBoolsAreEqual (false, returnsFalse() || returnsFalse() || returnsFalse());
    assertBoolsAreEqual (true, returnsTrue() || returnsFalse() || returnsFalse());
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_MixedAndOrWithFunctions(t *testing.T) {
	safeRun(t, `
bool returnsFalse () { return false; }
bool returnsTrue () { return true; }
void main () {
    assertBoolsAreEqual (true, (returnsTrue() || returnsFalse()) && returnsTrue());
    assertBoolsAreEqual (false, (returnsFalse() && returnsTrue()) || returnsFalse());
    assertBoolsAreEqual (true, returnsFalse() || (returnsTrue() && returnsTrue()));
    assertBoolsAreEqual (false, returnsTrue() && (returnsFalse() || returnsFalse()));
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_BoolFunctionWithNotAndAnd(t *testing.T) {
	safeRun(t, `
bool isReadingI2C () { return false; }
bool availableI2C () { return true; }
void main () {
    assertBoolsAreEqual (false, isReadingI2C() && !availableI2C());
    assertBoolsAreEqual (false, !isReadingI2C() && availableI2C() && isReadingI2C());
    assertBoolsAreEqual (true, !isReadingI2C() && availableI2C());
    assertBoolsAreEqual (true, !isReadingI2C() || availableI2C());
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_NonBooleanTypesInLogicalExpressions(t *testing.T) {
	safeRun(t, `
void main () {
    int x = 5;
    int y = 0;
    int z = 3;
    assertBoolsAreEqual (false, x && y);
    assertBoolsAreEqual (true, x && z);
    assertBoolsAreEqual (true, x || y);
    assertBoolsAreEqual (false, y && x);
    assertBoolsAreEqual (true, y || x);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_LogicalExpressionsInIfConditions(t *testing.T) {
	safeRun(t, `
bool returnsFalse () { return false; }
bool returnsTrue () { return true; }
void main () {
    int result = 0;
    if (returnsTrue() && returnsTrue()) { result = 1; }
    assertAreEqual (1, result);

    result = 0;
    if (returnsFalse() && returnsTrue()) { result = 1; }
    assertAreEqual (0, result);

    result = 0;
    if (returnsFalse() || returnsTrue()) { result = 1; }
    assertAreEqual (1, result);

    result = 0;
    if (returnsFalse() || returnsFalse()) { result = 1; }
    assertAreEqual (0, result);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_LogicalExpressionsInWhileConditions(t *testing.T) {
	safeRun(t, `
int counter = 0;
bool keepGoing () { return counter < 3; }
bool alwaysTrue () { return true; }
void main () {
    while (keepGoing() && alwaysTrue()) {
        counter = counter + 1;
    }
    assertAreEqual (3, counter);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_AndOrResultUsedInAssignment(t *testing.T) {
	safeRun(t, `
bool returnsFalse () { return false; }
bool returnsTrue () { return true; }
void main () {
    bool a = returnsTrue() && returnsFalse();
    bool b = returnsTrue() || returnsFalse();
    bool c = returnsFalse() && returnsTrue();
    bool d = returnsFalse() || returnsTrue();
    assertBoolsAreEqual (false, a);
    assertBoolsAreEqual (true, b);
    assertBoolsAreEqual (false, c);
    assertBoolsAreEqual (true, d);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_LogicTests_RepeatedLogicalOpsInLoop(t *testing.T) {
	safeRun(t, `
bool returnsFalse () { return false; }
bool returnsTrue () { return true; }
void main () {
    int i;
    for (i = 0; i < 10; i = i + 1) {
        assertBoolsAreEqual (false, returnsFalse() && returnsTrue());
        assertBoolsAreEqual (true, returnsTrue() || returnsFalse());
        assertBoolsAreEqual (true, returnsTrue() && !returnsFalse());
        assertBoolsAreEqual (false, returnsFalse() || returnsFalse());
    }
}
	`, newArduinoTestMachineInfo(t))
}

//endregion

//region --- InterpreterTests ---

// ============================================================================
// InterpreterTests — from InterpreterTests.cs
// ============================================================================

func Test_InterpreterTests_InfiniteLoopStopsEventually(t *testing.T) {
	safeRun(t, `
void main () {
	while (true) {
	}
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_MutualRecursive(t *testing.T) {
	safeRun(t, `
int m (int);

int f (int n) {
	return (n == 0) ? 1 : n - m (f (n - 1));
}
int m (int n) {
	return (n == 0) ? 0 : n - f (m (n - 1));
}
void main () {
	assertAreEqual (1, f (0));
	assertAreEqual (1, f (1));
	assertAreEqual (2, f (2));
	assertAreEqual (2, f (3));
	assertAreEqual (3, f (4));
	assertAreEqual (3, f (5));
	assertAreEqual (4, f (6));
	assertAreEqual (5, f (7));

	assertAreEqual (0, m (0));
	assertAreEqual (0, m (1));
	assertAreEqual (1, m (2));
	assertAreEqual (2, m (3));
	assertAreEqual (2, m (4));
	assertAreEqual (3, m (5));
	assertAreEqual (4, m (6));
	assertAreEqual (4, m (7));
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_Recursive(t *testing.T) {
	safeRun(t, `
unsigned long fib (unsigned long n) {
	if (n == 0 || n == 1) {
		return n;
	}
	else {
		return fib (n - 1) + fib (n - 2);
	}
}
void main () {
	assertAreEqual (0, fib (0));
	assertAreEqual (1, fib (1));
	assertAreEqual (1, fib (2));
	assertAreEqual (2, fib (3));
	assertAreEqual (3, fib (4));
	assertAreEqual (5, fib (5));
	assertAreEqual (8, fib (6));
	assertAreEqual (13, fib (7));
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_OverwriteArgs(t *testing.T) {
	safeRun(t, `
int abs (int x) {
	if (x < 0) x = -x;
	return x;
}
void main () {
	assertAreEqual (0, abs(0));
	assertAreEqual (101, abs(-101));
	assertAreEqual (101, abs(101));
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_VoidFunctionCalls(t *testing.T) {
	safeRun(t, `
int output = 0;
void print (int v) {
	output += v;
}
void main () {
	print (1);
	print (2);
	print (3);
	assertAreEqual (6, output);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_FunctionCallsWithValues(t *testing.T) {
	safeRun(t, `
int mulMulDiv (long m1, long m2, long d) {
	return (m1 * m2) / d;
}

void main () {
	assertAreEqual (66, mulMulDiv (2, 100, 3));
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_VoidReturnEarlyOut(t *testing.T) {
	safeRun(t, `
int x = 0;
void foo () {
	x = 42;
	return;
	x = 99;
}
void main () {
	foo ();
	assertAreEqual (42, x);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_VoidReturnStackCorrectAfterEarlyOut(t *testing.T) {
	safeRun(t, `
int x = 0;
void bar () {
	x = 10;
	return;
	x = 20;
}
int add (int a, int b) {
	return a + b;
}
void main () {
	int before = add (1, 2);
	bar ();
	int after = add (3, 4);
	assertAreEqual (3, before);
	assertAreEqual (7, after);
	assertAreEqual (10, x);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_ForLoop(t *testing.T) {
	safeRun(t, `
void main () {
	int acc;
	int i;
	for (acc = 0, i = -10; i <= 10; i += 2) {
		acc = acc + 1;
	}
	assertAreEqual (11, acc);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_ForLoopWithBreak(t *testing.T) {
	safeRun(t, `
void main () {
	int i;
	for (i = 0; i <= 10; i++) {
		if (i >= 5)
            break;
	}
	assertAreEqual (5, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_AintNoLoopForBreak(t *testing.T) {
	safeRunFailed(t, `
void main () {
    break;
}
	`, newArduinoTestMachineInfo(t))
}

func Test_InterpreterTests_AintNoLoopForContinue(t *testing.T) {
	safeRunFailed(t, `
void main () {
    continue;
}
	`, newArduinoTestMachineInfo(t))
}

func Test_InterpreterTests_ForLoopWithContinue(t *testing.T) {
	safeRun(t, `
void main () {
    int otherI = 0;
	int i;
	for (i = 0; i <= 10; i++) {
		if (i >= 5) {
            continue;
        }
        otherI++;
	}
	assertAreEqual (5, otherI);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_ForLoopInfinite(t *testing.T) {
	safeRun(t, `
void main () {
	int i = 0;
	for (;;) {
		i++;
		if (i >= 10) break;
	}
	assertAreEqual (10, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_ForLoopEmptyCondition(t *testing.T) {
	safeRun(t, `
void main () {
	int i;
	for (i = 0; ; i++) {
		if (i >= 5) break;
	}
	assertAreEqual (5, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_ForLoopEmptyIncrement(t *testing.T) {
	safeRun(t, `
void main () {
	int i;
	for (i = 0; i < 10;) {
		i++;
	}
	assertAreEqual (10, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_ForLoopEmptyInit(t *testing.T) {
	safeRun(t, `
void main () {
	int i = 0;
	for (; i < 5; i++) {
	}
	assertAreEqual (5, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_WhileLoopWithBreak(t *testing.T) {
	safeRun(t, `
void main () {
	int i = 0;
    while (i < 10) {
        i++;
        if (i == 5)
            break;
    }
	assertAreEqual (5, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_WhileLoopWithContinue(t *testing.T) {
	safeRun(t, `
void main () {
	int i = 0;
    int c = 0;
    while (i < 10) {
        i++;
        if (i > 5)
            continue;
        c++;
    }
	assertAreEqual (5, c);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_DoWhileOnce(t *testing.T) {
	safeRun(t, `
void main () {
	int i = 0;
    do {
        i++;
    } while (i > 1000);
	assertAreEqual (1, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_DoWhileLoopWithBreak(t *testing.T) {
	safeRun(t, `
void main () {
	int i = 0;
    do {
        i++;
        if (i == 5)
            break;
    } while (i < 10);
	assertAreEqual (5, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_DoWhileLoopWithContinue(t *testing.T) {
	safeRun(t, `
void main () {
	int i = 0;
    int c = 0;
    do {
        i++;
        if (i > 5)
            continue;
        c++;
    } while (i < 10);
	assertAreEqual (5, c);
    assertAreEqual (10, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_SizeofInt(t *testing.T) {
	safeRun(t, `
void main () {
	int s = sizeof(int);
	assertAreEqual (4, s);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_SizeofSizeofInt(t *testing.T) {
	safeRun(t, `
void main () {
	int s = sizeof(sizeof(int));
	assertAreEqual (4, s);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_SizeofIntPtr(t *testing.T) {
	safeRun(t, `
void main () {
	int s = sizeof(int*);
	assertAreEqual (4, s);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_SizeofLongInt(t *testing.T) {
	safeRun(t, `
void main () {
	int s = sizeof(long int);
	assertAreEqual (4, s);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_SizeofArray(t *testing.T) {
	safeRun(t, `
int array[] = { 0, 1, 2, 3, 4 };
void main () {
	int sa = sizeof(array);
	assertAreEqual (20, sa);
	int num = sa / sizeof(array[0]);
    int num2 = sa / sizeof(int);
	assertAreEqual (5, num);
    assertAreEqual (5, num2);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_InternalFunctionMemcmpWorks(t *testing.T) {
	safeRun(t, `
int memcmp (const void *s1, const void *s2, int n);
int ones[5] = { 1, 1, 1, 1, 1 };
int ones2[5] = { 1, 1, 1, 1, 1 };
int twos[5] = { 2, 2, 2, 2, 2 };
void main () {
	assertAreEqual (0, memcmp(ones, ones2, sizeof(ones)));
	assertAreEqual (0, memcmp(ones2, ones, sizeof(ones)));
	assertAreEqual (0, memcmp(ones, ones, sizeof(ones)));
	assertAreEqual (0, memcmp(ones2, ones2, sizeof(ones)));
	assertAreEqual (0, memcmp(twos, twos, sizeof(twos)));
	assertAreEqual (-1, memcmp(ones, twos, sizeof(ones)));
	assertAreEqual (1, memcmp(twos, ones, sizeof(ones)));
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_LocalVariableInitialization(t *testing.T) {
	safeRun(t, `
void main () {
	int a = 4;
	int b = 8;
	int c = a + b;
	assertAreEqual (12, c);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_GlobalVariableInitialization(t *testing.T) {
	safeRun(t, `
int a = 4;
int b = 8;
int c = a + b;
void main () {
    assertAreEqual (12, c);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_AddressOfLocal(t *testing.T) {
	safeRun(t, `
void main () {
    int a = 4;
    int *pa = &a;
    assertAreEqual (4, *pa);
    a = *pa + 1;
    assertAreEqual (5, *pa);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_AddressOfGlobal(t *testing.T) {
	safeRun(t, `
int a = 0;
void main () {
    int *pa = &a;
    assertAreEqual (0, *pa);
    a = *pa + 1;
    assertAreEqual (1, *pa);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_PreDecrement(t *testing.T) {
	safeRun(t, `
void main () {
    int a = 100;
    assertAreEqual (99, --a);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_PreIncrement(t *testing.T) {
	safeRun(t, `
void main () {
    int a = 100;
    assertAreEqual (101, ++a);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_PostDecrement(t *testing.T) {
	safeRun(t, `
void main () {
    int a = 100;
    assertAreEqual (100, a--);
    assertAreEqual (99, a);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_PostIncrement(t *testing.T) {
	safeRun(t, `
void main () {
    int a = 100;
    assertAreEqual (100, a++);
    assertAreEqual (101, a);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_PostIncrementPointer(t *testing.T) {
	safeRun(t, `
int a[] = { 10, 11, 12 };
void main () {
    int* p = a;
    assertAreEqual (10, *p++);
    assertAreEqual (11, *p++);
    assertAreEqual (12, *p++);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_PostDecrementPointer(t *testing.T) {
	safeRun(t, `
int a[] = { 10, 11, 12 };
void main () {
    int* p = a + 2;
    assertAreEqual (12, *p--);
    assertAreEqual (11, *p--);
    assertAreEqual (10, *p--);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_BoolAssignment(t *testing.T) {
	safeRun(t, `
void main () {
    bool a = false;
    assertAreEqual (false, a);
    assertAreEqual ((bool)0, a);
    a = true;
    assertAreEqual (true, a);
    assertAreEqual ((bool)1, a);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_BoolLoopEnd(t *testing.T) {
	safeRun(t, `
void main () {
    int i = 0;
    bool b = true;
    while (b) {
        i++;
        b = i < 10;
    }    
    assertAreEqual (false, b);
    assertAreEqual (10, i);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_ArrayElementAssignment(t *testing.T) {
	safeRun(t, `
int a[] = { 10, 11, 12, 13 };
void main () {
	assertAreEqual (10, a[0]);
	a[0] = 42;
	assertAreEqual (42, a[0]);
	assertAreEqual (12, a[2]);
	a[2] *= 1000;
	assertAreEqual (12000, a[2]);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_PointerAssignment(t *testing.T) {
	safeRun(t, `
int a[] = { 10, 11, 12, 13 };
void assign(int *p) { *p = 42; }
void main () {
	assertAreEqual (10, a[0]);
	assign(&a[0]);
	assertAreEqual (42, a[0]);

	assertAreEqual (12, a[2]);
	assign(a + 2);
	assertAreEqual (42, a[2]);

	assertAreEqual (13, a[3]);
	assign(3 + a);
	assertAreEqual (42, a[3]);

	int c = 33;
	assertAreEqual (33, c);
	assign(&c);
	assertAreEqual (42, c);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_VoidCallbackFunction(t *testing.T) {
	safeRun(t, `
int result = 0;
void callback(int x) {
	result = 10 * x;
}
void callCallback(void (*cb)(int), int cbx) {
	cb(cbx);
}
void main () {
	callCallback(callback, 12);
	assertAreEqual(120, result);
}
	`, newTestMachineInfo(t))
}

func Test_InterpreterTests_IntCallbackFunction(t *testing.T) {
	safeRun(t, `
int callback(int x) {
	return 10 * x;
}
int callCallback(int (*cb)(int), int cbx) {
	return cb(cbx);
}
void main () {
	int result = callCallback(callback, 123);
	assertAreEqual(1230, result);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- StructLayoutTests ---

// ============================================================================
// StructLayoutTests — from StructLayoutTests.cs
// ============================================================================

//endregion

//region --- VTableTypeTests ---

// ============================================================================
// VTableTypeTests — from VTableTypeTests.cs
// ============================================================================

//endregion

//region --- OperatorOverloadTests ---

// ============================================================================
// OperatorOverloadTests — from OperatorOverloadTests.cs
// ============================================================================

func Test_OperatorOverloadTests_ParseOperatorEquals(t *testing.T) {
	_ = safeRunParse(t, `
struct V {
    int x;
    bool operator==(int other);
};
void main() {}
	`)
}

func Test_OperatorOverloadTests_ParseOperatorSubscript(t *testing.T) {
	_ = safeRunParse(t, `
struct V {
    int data[10];
    int operator[](int index);
};
void main() {}
	`)
}

func Test_OperatorOverloadTests_ParseMultipleOperators(t *testing.T) {
	_ = safeRunParse(t, `
struct V {
    int x;
    int operator+(int other);
    int operator-(int other);
    int operator*(int other);
    bool operator==(int other);
    bool operator!=(int other);
    bool operator<(int other);
    int operator[](int i);
    int operator+=(int other);
};
void main() {}
	`)
}

func Test_OperatorOverloadTests_ParseOperatorCallParens(t *testing.T) {
	_ = safeRunParse(t, `
struct Functor {
    int operator()(int x);
};
void main() {}
	`)
}

func Test_OperatorOverloadTests_ParseOperatorBitwiseAndShift(t *testing.T) {
	_ = safeRunParse(t, `
struct V {
    int x;
    int operator&(int other);
    int operator|(int other);
    int operator^(int other);
    int operator<<(int other);
    int operator>>(int other);
    int operator~();
};
void main() {}
	`)
}

func Test_OperatorOverloadTests_ParseOperatorIncDec(t *testing.T) {
	_ = safeRunParse(t, `
struct V {
    int x;
    int operator++();
    int operator--();
};
void main() {}
	`)
}

func Test_OperatorOverloadTests_ParseOperatorAssignment(t *testing.T) {
	_ = safeRunParse(t, `
struct V {
    int x;
    int operator=(int other);
    int operator+=(int other);
    int operator-=(int other);
    int operator*=(int other);
    int operator/=(int other);
};
void main() {}
	`)
}

func Test_OperatorOverloadTests_MemberOperatorPlus(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    V operator+(V other);
};
V V::operator+(V other) {
    V r;
    r.x = this->x + other.x;
    return r;
}
void main() {
    V a; a.x = 3;
    V b; b.x = 4;
    V c = a + b;
    assertAreEqual(7, c.x);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_OperatorEquals(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    bool operator==(V other);
};
bool V::operator==(V other) { return this->x == other.x; }
void main() {
    V a; a.x = 5;
    V b; b.x = 5;
    V c; c.x = 6;
    assertAreEqual(1, a == b);
    assertAreEqual(0, a == c);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_ChainedOperators(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    V operator+(V other);
};
V V::operator+(V other) {
    V r;
    r.x = this->x + other.x;
    return r;
}
void main() {
    V a; a.x = 1;
    V b; b.x = 2;
    V c; c.x = 3;
    V d = a + b + c;
    assertAreEqual(6, d.x);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_FreeStandingOperatorExecution(t *testing.T) {
	safeRun(t, `
struct V { int x; };
V operator+(V a, V b) {
    V r;
    r.x = a.x + b.x;
    return r;
}
void main() {
    V a; a.x = 10;
    V b; b.x = 20;
    V c = a + b;
    assertAreEqual(30, c.x);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_MixedTypeOperator(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    V operator+(int n);
};
V V::operator+(int n) {
    V r;
    r.x = this->x + n;
    return r;
}
void main() {
    V a; a.x = 5;
    V b = a + 10;
    assertAreEqual(15, b.x);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_OperatorSubscriptExecution(t *testing.T) {
	safeRun(t, `
struct Vec {
    int data[3];
    int operator[](int i);
};
int Vec::operator[](int i) {
    return this->data[i];
}
void main() {
    Vec v;
    v.data[0] = 10;
    v.data[1] = 20;
    v.data[2] = 30;
    assertAreEqual(20, v[1]);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_ComparisonOperatorsExecution(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    bool operator<(V other);
    bool operator>(V other);
    bool operator!=(V other);
};
bool V::operator<(V other) { return this->x < other.x; }
bool V::operator>(V other) { return this->x > other.x; }
bool V::operator!=(V other) { return this->x != other.x; }
void main() {
    V a; a.x = 3;
    V b; b.x = 5;
    assertAreEqual(1, a < b);
    assertAreEqual(0, a > b);
    assertAreEqual(1, a != b);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_UnaryOperatorMinus(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    V operator-();
};
V V::operator-() {
    V r;
    r.x = -(this->x);
    return r;
}
void main() {
    V a; a.x = 5;
    V b = -a;
    assertAreEqual(-5, b.x);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_AllArithmeticOperators(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    V operator+(V o);
    V operator-(V o);
    V operator*(V o);
    V operator/(V o);
    V operator%(V o);
};
V V::operator+(V o) { V r; r.x = this->x + o.x; return r; }
V V::operator-(V o) { V r; r.x = this->x - o.x; return r; }
V V::operator*(V o) { V r; r.x = this->x * o.x; return r; }
V V::operator/(V o) { V r; r.x = this->x / o.x; return r; }
V V::operator%(V o) { V r; r.x = this->x % o.x; return r; }
void main() {
    V a; a.x = 20;
    V b; b.x = 3;
    V r1 = a + b; assertAreEqual(23, r1.x);
    V r2 = a - b; assertAreEqual(17, r2.x);
    V r3 = a * b; assertAreEqual(60, r3.x);
    V r4 = a / b; assertAreEqual(6, r4.x);
    V r5 = a % b; assertAreEqual(2, r5.x);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_ConstRefOperator(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    V operator+(const V& other);
};
V V::operator+(const V& other) {
    V r;
    r.x = this->x + other.x;
    return r;
}
void main() {
    V a; a.x = 3;
    V b; b.x = 4;
    V c = a + b;
    assertAreEqual(7, c.x);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_ConstRefComparisonOperator(t *testing.T) {
	safeRun(t, `
struct V {
    int x;
    bool operator==(const V& other);
    bool operator<(const V& other);
};
bool V::operator==(const V& other) { return this->x == other.x; }
bool V::operator<(const V& other) { return this->x < other.x; }
void main() {
    V a; a.x = 5;
    V b; b.x = 5;
    V c; c.x = 10;
    assertAreEqual(1, a == b);
    assertAreEqual(0, a == c);
    assertAreEqual(1, a < c);
    assertAreEqual(0, c < a);
}
	`, newTestMachineInfo(t))
}

func Test_OperatorOverloadTests_ClassWithCtorAndOperator(t *testing.T) {
	safeRun(t, `
class C {
public:
    int x;
    C(int x);
    C operator+(C other);
};
C::C(int x) { this->x = x; }
C C::operator+(C other) {
    C r(this->x + other.x);
    return r;
}
void main() {
    C a(3);
    C b(4);
    C c = a + b;
    assertAreEqual(7, c.x);
}
	`, newTestMachineInfo(t))
}

//endregion

//region --- IntegerTests ---

// ============================================================================
// IntegerTests — from IntegerTests.cs
// ============================================================================

func Test_IntegerTests_ShiftLeftByteOverflowsOn16BitInt(t *testing.T) {
	safeRun(t, `
void main () {
    byte b = 7;
    long result_no_cast = b << 16;
    assert32AreEqual (0L, result_no_cast);

    long result_cast = (long)b << 16;
    assert32AreEqual (458752L, result_cast);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_IntegerTests_ShiftLeftBitBoundary16BitInt(t *testing.T) {
	safeRun(t, `
void main () {
    byte b = 1;

    assertAreEqual (-32768, b << 15);

    assertAreEqual (16384, b << 14);

    unsigned int u = 1;
    assertU16AreEqual (32768, u << 15);

    byte high = 0xAB;
    byte low = 0xCD;
    assertU16AreEqual (0xABCD, ((unsigned int)high << 8) | low);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_IntegerTests_ShiftResultTypeDependsOnlyOnLeftOperand(t *testing.T) {
	safeRun(t, `
void main () {
    byte b = 1;
    long shift = 8;
    assertAreEqual (256, b << shift);

    long l = 1;
    byte s = 20;
    assert32AreEqual (1048576L, l << s);

    unsigned long ul = 0xFF;
    char sc = 16;
    assertU32AreEqual (16711680, ul << sc);

    int i = 1;
    long sl = 12;
    assertAreEqual (4096, i << sl);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_IntegerTests_ShiftRightSignedUnsignedBehavior(t *testing.T) {
	safeRun(t, `
void main () {
    int neg = -1024;
    assertAreEqual (-128, neg >> 3);

    unsigned int uneg = 0xFC00;
    assertU16AreEqual (0x1F80, uneg >> 3);

    long lneg = -262144L;
    assert32AreEqual (-32768L, lneg >> 3);

    unsigned long val = 0x00051234;
    byte high = (byte)(val >> 16);
    unsigned int low = (unsigned int)(val & 0xFFFF);
    assertAreEqual (5, high);
    assertU16AreEqual (0x1234, low);
}
	`, newArduinoTestMachineInfo(t))
}

func Test_IntegerTests_StdInts(t *testing.T) {
	safeRun(t, `
#include <stdint.h>
int8_t byteValue = 42;
void main() {
    assertAreEqual(42, byteValue);
}
	`, newArduinoTestMachineInfo(t))
}

//endregion

//region --- DeclarationTests ---

// ============================================================================
// DeclarationTests — from DeclarationTests.cs
// ============================================================================

func Test_DeclarationTests_VarInitializationOrder(t *testing.T) {
	safeRun(t, `
void main() {
    int x = 42;
    assertAreEqual(42, x);
    x = 32;
    assertAreEqual(32, x);
    int y = x * 100;
    assertAreEqual(3200, y);
    y += 1;
    assertAreEqual(3201, y);
}
	`, newTestMachineInfo(t))
}

func Test_DeclarationTests_ValidLongDoubleIsOk(t *testing.T) {
	safeRun(t, `
void main() { long double x = 1.0; }
	`, newTestMachineInfo(t))
}

func Test_DeclarationTests_ValidLongLongIntIsOk(t *testing.T) {
	safeRun(t, `
void main() { long long int x = 0; }
	`, newTestMachineInfo(t))
}

//endregion
