// Code generated by "stringer -type=TokenKind -output ./token_string.go"; DO NOT EDIT.

package cxxParser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenKindYYErrorCode-256]
	_ = x[TokenKindIDENTIFIER-257]
	_ = x[TokenKindCONSTANT-258]
	_ = x[TokenKindSTRING_LITERAL-259]
	_ = x[TokenKindSIZEOF-260]
	_ = x[TokenKindPTR_OP-261]
	_ = x[TokenKindINC_OP-262]
	_ = x[TokenKindDEC_OP-263]
	_ = x[TokenKindLEFT_OP-264]
	_ = x[TokenKindRIGHT_OP-265]
	_ = x[TokenKindLE_OP-266]
	_ = x[TokenKindGE_OP-267]
	_ = x[TokenKindEQ_OP-268]
	_ = x[TokenKindNE_OP-269]
	_ = x[TokenKindCOLONCOLON-270]
	_ = x[TokenKindAND_OP-271]
	_ = x[TokenKindOR_OP-272]
	_ = x[TokenKindMUL_ASSIGN-273]
	_ = x[TokenKindDIV_ASSIGN-274]
	_ = x[TokenKindMOD_ASSIGN-275]
	_ = x[TokenKindADD_ASSIGN-276]
	_ = x[TokenKindSUB_ASSIGN-277]
	_ = x[TokenKindLEFT_ASSIGN-278]
	_ = x[TokenKindRIGHT_ASSIGN-279]
	_ = x[TokenKindBINARY_AND_ASSIGN-280]
	_ = x[TokenKindBINARY_XOR_ASSIGN-281]
	_ = x[TokenKindBINARY_OR_ASSIGN-282]
	_ = x[TokenKindAND_ASSIGN-283]
	_ = x[TokenKindOR_ASSIGN-284]
	_ = x[TokenKindTYPE_NAME-285]
	_ = x[TokenKindPUBLIC-286]
	_ = x[TokenKindPRIVATE-287]
	_ = x[TokenKindPROTECTED-288]
	_ = x[TokenKindVIRTUAL-289]
	_ = x[TokenKindOVERRIDE-290]
	_ = x[TokenKindOPERATOR-291]
	_ = x[TokenKindTYPEDEF-292]
	_ = x[TokenKindEXTERN-293]
	_ = x[TokenKindSTATIC-294]
	_ = x[TokenKindAUTO-295]
	_ = x[TokenKindREGISTER-296]
	_ = x[TokenKindINLINE-297]
	_ = x[TokenKindRESTRICT-298]
	_ = x[TokenKindCHAR-299]
	_ = x[TokenKindSHORT-300]
	_ = x[TokenKindINT-301]
	_ = x[TokenKindLONG-302]
	_ = x[TokenKindSIGNED-303]
	_ = x[TokenKindUNSIGNED-304]
	_ = x[TokenKindFLOAT-305]
	_ = x[TokenKindDOUBLE-306]
	_ = x[TokenKindCONST-307]
	_ = x[TokenKindVOLATILE-308]
	_ = x[TokenKindVOID-309]
	_ = x[TokenKindBOOL-310]
	_ = x[TokenKindCOMPLEX-311]
	_ = x[TokenKindIMAGINARY-312]
	_ = x[TokenKindTRUE-313]
	_ = x[TokenKindFALSE-314]
	_ = x[TokenKindSTRUCT-315]
	_ = x[TokenKindCLASS-316]
	_ = x[TokenKindUNION-317]
	_ = x[TokenKindENUM-318]
	_ = x[TokenKindELLIPSIS-319]
	_ = x[TokenKindCASE-320]
	_ = x[TokenKindDEFAULT-321]
	_ = x[TokenKindIF-322]
	_ = x[TokenKindELSE-323]
	_ = x[TokenKindSWITCH-324]
	_ = x[TokenKindWHILE-325]
	_ = x[TokenKindDO-326]
	_ = x[TokenKindFOR-327]
	_ = x[TokenKindGOTO-328]
	_ = x[TokenKindCONTINUE-329]
	_ = x[TokenKindBREAK-330]
	_ = x[TokenKindRETURN-331]
	_ = x[TokenKindEOL-332]
}

const _TokenKind_name = "TokenKindYYErrorCodeTokenKindIDENTIFIERTokenKindCONSTANTTokenKindSTRING_LITERALTokenKindSIZEOFTokenKindPTR_OPTokenKindINC_OPTokenKindDEC_OPTokenKindLEFT_OPTokenKindRIGHT_OPTokenKindLE_OPTokenKindGE_OPTokenKindEQ_OPTokenKindNE_OPTokenKindCOLONCOLONTokenKindAND_OPTokenKindOR_OPTokenKindMUL_ASSIGNTokenKindDIV_ASSIGNTokenKindMOD_ASSIGNTokenKindADD_ASSIGNTokenKindSUB_ASSIGNTokenKindLEFT_ASSIGNTokenKindRIGHT_ASSIGNTokenKindBINARY_AND_ASSIGNTokenKindBINARY_XOR_ASSIGNTokenKindBINARY_OR_ASSIGNTokenKindAND_ASSIGNTokenKindOR_ASSIGNTokenKindTYPE_NAMETokenKindPUBLICTokenKindPRIVATETokenKindPROTECTEDTokenKindVIRTUALTokenKindOVERRIDETokenKindOPERATORTokenKindTYPEDEFTokenKindEXTERNTokenKindSTATICTokenKindAUTOTokenKindREGISTERTokenKindINLINETokenKindRESTRICTTokenKindCHARTokenKindSHORTTokenKindINTTokenKindLONGTokenKindSIGNEDTokenKindUNSIGNEDTokenKindFLOATTokenKindDOUBLETokenKindCONSTTokenKindVOLATILETokenKindVOIDTokenKindBOOLTokenKindCOMPLEXTokenKindIMAGINARYTokenKindTRUETokenKindFALSETokenKindSTRUCTTokenKindCLASSTokenKindUNIONTokenKindENUMTokenKindELLIPSISTokenKindCASETokenKindDEFAULTTokenKindIFTokenKindELSETokenKindSWITCHTokenKindWHILETokenKindDOTokenKindFORTokenKindGOTOTokenKindCONTINUETokenKindBREAKTokenKindRETURNTokenKindEOL"

var _TokenKind_index = [...]uint16{0, 20, 39, 56, 79, 94, 109, 124, 139, 155, 172, 186, 200, 214, 228, 247, 262, 276, 295, 314, 333, 352, 371, 391, 412, 438, 464, 489, 508, 526, 544, 559, 575, 593, 609, 626, 643, 659, 674, 689, 702, 719, 734, 751, 764, 778, 790, 803, 818, 835, 849, 864, 878, 895, 908, 921, 937, 955, 968, 982, 997, 1011, 1025, 1038, 1055, 1068, 1084, 1095, 1108, 1123, 1137, 1148, 1160, 1173, 1190, 1204, 1219, 1231}

func (i TokenKind) String() string {
	idx := int(i) - 256
	if i < 256 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
