// Code generated by bison 3.3.2 on Fri, 22 May 2026 01:16:03 +0800, DO NOT EDIT.
// -go:generate bison --output=zend_language_parser_.c -v -d bison.y
package phpParser

import "unsafe"


//goland:noinspection GoVetUnsafePointer,GoBoolExpressions,GoSnakeCaseUsage
func (p *Parser) Parse() (ret int, err error) {
	/* The stacks and their tools:
	   'yyss': related to states.
	   'yyvs': related to semantic values.

	   Refer to the stacks through separate pointers, to allow yyoverflow
	   to reallocate them elsewhere.  */
	var yylval, yyval yySymType
	var tka AstTkn
	var tkn Token

	/* The state stack.  */
	yyssa := make([]int, YYINITDEPTH)
	/* The semantic value stack.  */
	yyvsa := make([]yySymType, YYINITDEPTH)

	yyn, yyssp, yyvsp := 0, 0, 0

	/* Lookahead token as an internal (translated) token number.  */
	yytoken, modifiers := 0, AstAttr(0)

	/* The number of symbols on the RHS of the reduced rule.
	   Keep to zero when no symbol should be popped.  */
	yylen := 0

	/* Number of syntax errors so far.  */
	/* Number of tokens to shift before error messages enabled.  */
	yystate, yyerrstatus, yynerrs := 0, 0, 0

	// YYDPRINTF ((stderr, "Starting parse\n"));

	/* The lookahead symbol.  */
	yychar := ID(YYEMPTY) /* Cause a token to be read.  */
	yyssp -= 1

yynewstate:
	yyssp += 1
	if yyssp >= len(yyssa)-1 {
		if len(yyssa) >= 1000 {
			err = p.yySyntaxError(tka, "memory exhausted", yyssa, yyssp, yytoken)
			return 3, err
		}
		nl := len(yyvsa) * 2
		if nl >= 1000 {
			nl = 1000
		}
		nyys := make([]yySymType, nl)
		copy(nyys, yyvsa)
		yyvsa = nyys

		nyya := make([]int, nl)
		copy(nyya, yyssa)
		yyssa = nyya
	}
	// YYDPRINTF ((stderr, "Entering state %d\n", yystate));

	yyssa[yyssp] = yystate
	if yystate == YYFINAL {
		goto yyacceptlab
	}

	yyn = int(yypact[yystate])
	if yyn == YYPACT_NINF {
		goto yydefault
	}

	/* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
	if yychar == YYEMPTY {
		// YYDPRINTF ((stderr, "Reading a token: "));
		// yychar = p.Lex(&yylval)
		p.cursor, tkn = p.lexer.Lex(p.cursor)
		tka = AstTkn(tkn - p.tknOffset)
		yychar = ID(tkn & UintCurFullTypMask)
		if yychar == T_ERROR {
			return 2, p.lexer.LastErr
		}

		yylval.tka = tka
		if tkn == p.lexer.tkvLast.t {
			yylval.ast = astCreateZvalAttr(tka, p.lexer.tkvLast.v, 0)
		} else {
			yylval.ast = nil
		}
	}

	if yychar <= YYEOF {
		yychar, yytoken = YYEOF, YYEOF
		// YYDPRINTF ((stderr, "Now at end of input.\n"));
	} else {
		yytoken = YYUNDEFTOK
		if uint(yychar) <= YYMAXUTOK {
			yytoken = int(yytranslate[yychar])
		}
		// YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
	}

	/* If the proper action on seeing token YYTOKEN is to reduce or to detect an error, take that action.  */
	yyn += yytoken
	if yyn < 0 || YYLAST < yyn || int(yycheck[yyn]) != yytoken {
		goto yydefault
	}

	yyn = int(yytable[yyn])
	if yyn <= 0 {
		if yyn == YYTABLE_NINF {
			goto yyerrlab
		}

		yyn = -yyn
		goto yyreduce
	}

	/* Count tokens shifted since error; after three, turn off error status.  */
	if yyerrstatus != 0 {
		yyerrstatus -= 1
	}

	// YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);

	yychar = YYEMPTY
	yystate = yyn
	yyvsp += 1
	yyvsa[yyvsp] = yylval

	goto yynewstate

yydefault:
	yyn = int(yydefact[yystate])
	if yyn == 0 {
		goto yyerrlab
	}
	goto yyreduce

yyreduce:
	/* yyn is the number of a rule to reduce with.  */
	yylen = int(yyr2[yyn])
	yyval = yyvsa[yyvsp+1-yylen]

	// YY_REDUCE_PRINT (yyn);
	switch yyn {
	case 2:
		{ p.rootAst = yyvsa[yyvsp].ast; yynerrs = 0 }
	case 84, 88, 89, 90, 91, 92, 93, 105, 106, 107, 108, 109, 110, 112, 113, 147, 148, 152, 153, 181, 187, 214, 217, 219, 221, 223, 224, 228, 230, 232, 252, 256, 267, 273, 274, 276, 277, 278, 280, 286, 288, 289, 292, 293, 300, 315, 316, 331, 332, 350, 404, 412, 413, 415, 473, 474, 478, 488, 496, 500, 514, 523, 524, 525, 528, 529, 531, 534, 536, 537, 541, 542, 543, 559, 560, 561, 563, 564, 565, 566, 567, 568, 570, 571, 576, 577, 578, 581, 592, 595, 600, 622, 623, 633:
		{ yyval.ast = yyvsa[yyvsp].ast }
	case 85, 188:
		{ zast, errLexT := p.lexTString(yyvsa[yyvsp].tka); if errLexT != nil { err = errLexT; goto yyabortlab }; yyval.ast = zast }
	case 86, 104, 145, 324, 341, 379, 610, 611:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 87, 146, 325, 378:
		if tka == 0 {
			tka = AstTkn((int(p.cursor<<16)|int(T_OPEN_TAG))-p.tknOffset)
		}
		{ yyval.ast = astCreateList0(tka, ZEND_AST_STMT_LIST) }
	case 94, 95:
		{ yyval.ast = yyvsa[yyvsp].ast; yyval.ast.Attr = ZEND_NAME_NOT_FQ }
	case 96:
		{ yyval.ast = yyvsa[yyvsp].ast; yyval.ast.Attr = ZEND_NAME_FQ }
	case 97:
		{ yyval.ast = yyvsa[yyvsp].ast; yyval.ast.Attr = ZEND_NAME_RELATIVE }
	case 98:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ATTRIBUTE, yyvsa[yyvsp].ast, nil) }
	case 99:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ATTRIBUTE, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 100:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_ATTRIBUTE_GROUP, yyvsa[yyvsp].ast) }
	case 101, 131, 133, 135, 143, 179, 185, 247, 251, 265, 283, 285, 296, 298, 305, 312, 317, 320, 336, 372, 392, 397, 401, 405, 512, 601:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 102:
		{ yyval.ast = yyvsa[yyvsp-2].ast; p.lexer.docComment = Token(int(yyvsa[yyvsp-3].tka) + p.tknOffset); }
	case 103:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_ATTRIBUTE_LIST, yyvsa[yyvsp].ast) }
	case 111, 121, 151, 161, 162, 163, 165, 183, 234, 235, 245, 262, 281, 294, 339, 342, 343, 353, 382, 388, 391, 526, 535, 538, 540, 569, 582, 593, 596, 621:
		{ yyval.ast = yyvsa[yyvsp-1].ast }
	case 114, 149, 266, 333, 497:
		{ yyval.ast = astWithAttributes(yyvsa[yyvsp].ast, yyvsa[yyvsp-1].ast) }
	case 115:
		{ yyval.ast = astCreate1(tka, ZEND_AST_HALT_COMPILER, p.astCreateZvalFromLong(tka, p.getScannedFileOffset())); p.stopLexing() }
	case 116:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NAMESPACE, yyvsa[yyvsp-1].ast, nil); p.lexer.docComment = 0 }
	case 117, 119:
		{ p.lexer.docComment = 0 }
	case 118:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NAMESPACE, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast) }
	case 120:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NAMESPACE, nil, yyvsa[yyvsp-1].ast) }
	case 122, 124:
		{ yyval.ast = yyvsa[yyvsp-1].ast; yyval.ast.Attr = AstAttr(yyvsa[yyvsp-2].num) }
	case 123:
		{ yyval.ast = yyvsa[yyvsp-1].ast; yyval.ast.Attr = ZEND_SYMBOL_CLASS }
	case 125:
		{ yyval.num = ZEND_SYMBOL_FUNCTION }
	case 126:
		{ yyval.num = ZEND_SYMBOL_CONST }
	case 127, 128:
		{ yyval.ast = astCreate2(tka, ZEND_AST_GROUP_USE, yyvsa[yyvsp-5].ast, yyvsa[yyvsp-2].ast) }
	case 132, 134, 136:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_USE, yyvsa[yyvsp].ast) }
	case 137:
		{ yyval.ast = yyvsa[yyvsp].ast; yyval.ast.Attr = ZEND_SYMBOL_CLASS }
	case 138:
		{ yyval.ast = yyvsa[yyvsp].ast; yyval.ast.Attr = AstAttr(yyvsa[yyvsp-1].num) }
	case 139, 141:
		{ yyval.ast = astCreate2(tka, ZEND_AST_USE_ELEM, yyvsa[yyvsp].ast, nil) }
	case 140, 142:
		{ yyval.ast = astCreate2(tka, ZEND_AST_USE_ELEM, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 144:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_CONST_DECL, yyvsa[yyvsp].ast) }
	case 150:
		{ yyval.ast, err = nil, errHalt; p.HandelError(yyval.tka, err); goto yyerrorlab }
	case 154:
		{ yyval.ast = astCreate2(tka, ZEND_AST_WHILE, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 155:
		{ yyval.ast = astCreate2(tka, ZEND_AST_DO_WHILE, yyvsa[yyvsp-5].ast, yyvsa[yyvsp-2].ast) }
	case 156:
		{ yyval.ast = astCreate4(tka, ZEND_AST_FOR, yyvsa[yyvsp-6].ast, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 157:
		{ yyval.ast = astCreate2(tka, ZEND_AST_SWITCH, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 158:
		{ yyval.ast = astCreate1(tka, ZEND_AST_BREAK, yyvsa[yyvsp-1].ast) }
	case 159:
		{ yyval.ast = astCreate1(tka, ZEND_AST_CONTINUE, yyvsa[yyvsp-1].ast) }
	case 160:
		{ yyval.ast = astCreate1(tka, ZEND_AST_RETURN, yyvsa[yyvsp-1].ast) }
	case 164, 399:
		{ yyval.ast = astCreate1(tka, ZEND_AST_ECHO, yyvsa[yyvsp].ast) }
	case 166:
		{ yyval.ast = yyvsa[yyvsp-3].ast }
	case 167:
		{ yyval.ast = astCreate4(tka, ZEND_AST_FOREACH, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-2].ast, nil, yyvsa[yyvsp].ast) }
	case 168:
		{ yyval.ast = astCreate4(tka, ZEND_AST_FOREACH, yyvsa[yyvsp-6].ast, yyvsa[yyvsp-2].ast, yyvsa[yyvsp-4].ast, yyvsa[yyvsp].ast) }
	case 169:
		{ if !p.handleEncodingDeclaration(yyvsa[yyvsp-1].ast) { goto yyerrorlab } }
	case 170:
		{ yyval.ast = astCreate2(tka, ZEND_AST_DECLARE, yyvsa[yyvsp-3].ast, yyvsa[yyvsp].ast) }
	case 171, 180, 182, 213, 216, 218, 220, 222, 272, 299, 337, 338, 352, 381, 387, 390, 400, 403, 510, 558, 599:
		{ yyval.ast = nil }
	case 172:
		{ yyval.ast = astCreate3(tka, ZEND_AST_TRY, yyvsa[yyvsp-3].ast, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 173:
		{ yyval.ast = astCreate1(tka, ZEND_AST_GOTO, yyvsa[yyvsp-1].ast) }
	case 174:
		{ yyval.ast = astCreate1(tka, ZEND_AST_LABEL, yyvsa[yyvsp-1].ast) }
	case 175:
		{ yyval.ast = astCreate1(tka, ZEND_AST_CAST_VOID, yyvsa[yyvsp-1].ast) }
	case 176:
		{ yyval.ast = astCreateList0(tka, ZEND_AST_CATCH_LIST) }
	case 177:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-8].ast, astCreate3(tka, ZEND_AST_CATCH, yyvsa[yyvsp-5].ast, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast)) }
	case 178, 335:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_NAME_LIST, yyvsa[yyvsp].ast) }
	case 184, 318, 321, 398:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_STMT_LIST, yyvsa[yyvsp].ast) }
	case 186:
		{ yyval.ast = astCreate1(tka, ZEND_AST_UNSET, yyvsa[yyvsp].ast) }
	case 189:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_FUNC_DECL, uint32(yyvsa[yyvsp-11].num|yyvsa[yyvsp].num), yyvsa[yyvsp-12].tka, p.getTknStr(yyvsa[yyvsp-9].tka), p.getTknStr(yyvsa[yyvsp-10].tka), yyvsa[yyvsp-7].ast, nil, yyvsa[yyvsp-2].ast, yyvsa[yyvsp-5].ast, nil); p.extraFnFlags = yyvsa[yyvsp-4].num }
	case 190, 192, 202, 268, 383, 508:
		{ yyval.num = 0 }
	case 191:
		{ yyval.num = ZEND_PARAM_REF }
	case 193:
		{ yyval.num = ZEND_PARAM_VARIADIC }
	case 194, 196, 207, 209, 211, 385, 503, 504, 520:
		{ yyval.tka = tka }
	case 195:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_CLASS, uint32(yyvsa[yyvsp-9].num), yyvsa[yyvsp-7].tka, p.getTknStr(yyvsa[yyvsp-3].tka), p.getTknStr(yyvsa[yyvsp-6].tka), yyvsa[yyvsp-5].ast, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast, nil, nil) }
	case 197:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_CLASS, 0, yyvsa[yyvsp-7].tka, p.getTknStr(yyvsa[yyvsp-3].tka), p.getTknStr(yyvsa[yyvsp-6].tka), yyvsa[yyvsp-5].ast, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast, nil, nil) }
	case 198, 203:
		{ yyval.num = yyvsa[yyvsp].num }
	case 199:
		{ yyval.num, err = p.classModifier(tka, yyvsa[yyvsp-1].num, yyvsa[yyvsp].num); if yyval.num == 0 { goto yyerrorlab } }
	case 200:
		{ yyval.num, err = p.anonymousClassModifier(tka, 0, yyvsa[yyvsp].num); if yyval.num == 0 { goto yyerrorlab } }
	case 201:
		{ yyval.num, err = p.anonymousClassModifier(tka, yyvsa[yyvsp-1].num, yyvsa[yyvsp].num); if yyval.num == 0 { goto yyerrorlab } }
	case 204:
		{ yyval.num = ZEND_ACC_EXPLICIT_ABSTRACT_CLASS }
	case 205:
		{ yyval.num = ZEND_ACC_FINAL }
	case 206:
		{ yyval.num = ZEND_ACC_READONLY_CLASS|ZEND_ACC_NO_DYNAMIC_PROPERTIES }
	case 208:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_CLASS, ZEND_ACC_TRAIT, yyvsa[yyvsp-5].tka, p.getTknStr(yyvsa[yyvsp-3].tka), p.getTknStr(yyvsa[yyvsp-4].tka), nil, nil, yyvsa[yyvsp-1].ast, nil, nil) }
	case 210:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_CLASS, ZEND_ACC_INTERFACE, yyvsa[yyvsp-6].tka, p.getTknStr(yyvsa[yyvsp-3].tka), p.getTknStr(yyvsa[yyvsp-5].tka), nil, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast, nil, nil) }
	case 212:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_CLASS, ZEND_ACC_ENUM|ZEND_ACC_FINAL, yyvsa[yyvsp-7].tka, p.getTknStr(yyvsa[yyvsp-3].tka), p.getTknStr(yyvsa[yyvsp-6].tka), nil, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast, nil, yyvsa[yyvsp-5].ast) }
	case 215:
		{ yyval.ast = astCreate4(tka, ZEND_AST_ENUM_CASE, yyvsa[yyvsp-2].ast, yyvsa[yyvsp-1].ast, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp-3].tka)), nil) }
	case 225:
		{ yyval.ast = astCreate1(tka, ZEND_AST_REF, yyvsa[yyvsp].ast) }
	case 226:
		{ yyval.ast = yyvsa[yyvsp-1].ast; yyval.ast.Attr = ZEND_ARRAY_SYNTAX_LIST }
	case 227, 533:
		{ yyval.ast = yyvsa[yyvsp-1].ast; yyval.ast.Attr = ZEND_ARRAY_SYNTAX_SHORT }
	case 229, 231, 233, 236, 237, 253, 260, 302, 307, 511, 626:
		{ yyval.ast = yyvsa[yyvsp-2].ast }
	case 238:
		{ yyval.ast = astCreateList0(tka, ZEND_AST_SWITCH_LIST) }
	case 239:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-4].ast, astCreate2(tka, ZEND_AST_SWITCH_CASE, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast)) }
	case 240:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-4].ast, astCreateEx2(tka, ZEND_AST_SWITCH_CASE, ZEND_ALT_CASE_SYNTAX, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast)) }
	case 241:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-3].ast, astCreate2(tka, ZEND_AST_SWITCH_CASE, nil, yyvsa[yyvsp].ast)) }
	case 242:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-3].ast, astCreateEx2(tka, ZEND_AST_SWITCH_CASE, ZEND_ALT_CASE_SYNTAX, nil, yyvsa[yyvsp].ast)) }
	case 243:
		{ yyval.ast = astCreate2(tka, ZEND_AST_MATCH, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast) }
	case 244:
		{ yyval.ast = astCreateList0(tka, ZEND_AST_MATCH_ARM_LIST) }
	case 246:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_MATCH_ARM_LIST, yyvsa[yyvsp].ast) }
	case 248:
		{ yyval.ast = astCreate2(tka, ZEND_AST_MATCH_ARM, yyvsa[yyvsp-3].ast, yyvsa[yyvsp].ast) }
	case 249:
		{ yyval.ast = astCreate2(tka, ZEND_AST_MATCH_ARM, nil, yyvsa[yyvsp].ast) }
	case 250, 402, 408:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_EXPR_LIST, yyvsa[yyvsp].ast) }
	case 254:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_IF, astCreate2(tka, ZEND_AST_IF_ELEM, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast)) }
	case 255:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-5].ast, astCreate2(tka, ZEND_AST_IF_ELEM, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast)) }
	case 257:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-2].ast, astCreate2(tka, ZEND_AST_IF_ELEM, nil, yyvsa[yyvsp].ast)) }
	case 258:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_IF, astCreate2(tka, ZEND_AST_IF_ELEM, yyvsa[yyvsp-3].ast, yyvsa[yyvsp].ast)) }
	case 259:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-6].ast, astCreate2(tka, ZEND_AST_IF_ELEM, yyvsa[yyvsp-3].ast, yyvsa[yyvsp].ast)) }
	case 261:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-5].ast, astCreate2(tka, ZEND_AST_IF_ELEM, nil, yyvsa[yyvsp-2].ast)) }
	case 263:
		{ yyval.ast = astCreateList0(tka, ZEND_AST_PARAM_LIST) }
	case 264:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_PARAM_LIST, yyvsa[yyvsp].ast) }
	case 269:
		{ yyval.num, err = p.modifierListToFlags(tka, ZEND_MODIFIER_TARGET_CPP, yyvsa[yyvsp].ast); if yyval.num == 0 { goto yyerrorlab } }
	case 270:
		{ yyval.ast = astCreateEx6(tka, ZEND_AST_PARAM, uint32(yyvsa[yyvsp-6].num|yyvsa[yyvsp-4].num|yyvsa[yyvsp-3].num), yyvsa[yyvsp-5].ast, yyvsa[yyvsp-2].ast, nil, nil, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp-1].tka)), yyvsa[yyvsp].ast) }
	case 271:
		{ yyval.ast = astCreateEx6(tka, ZEND_AST_PARAM, uint32(yyvsa[yyvsp-8].num|yyvsa[yyvsp-6].num|yyvsa[yyvsp-5].num), yyvsa[yyvsp-7].ast, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast, nil, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp-3].tka)), yyvsa[yyvsp].ast) }
	case 275, 287:
		{ yyval.ast = yyvsa[yyvsp].ast; yyval.ast.Attr |= ZEND_TYPE_NULLABLE }
	case 279:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_TYPE, IS_STATIC) }
	case 282, 295:
		{ yyval.ast = astCreateList2(tka, ZEND_AST_TYPE_UNION, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 284, 297:
		{ yyval.ast = astCreateList2(tka, ZEND_AST_TYPE_INTERSECTION, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 290:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_TYPE, IS_ARRAY) }
	case 291:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_TYPE, IS_CALLABLE) }
	case 301, 306, 530:
		{ yyval.ast = astCreateList0(tka, ZEND_AST_ARG_LIST) }
	case 303, 309:
		{ yyval.ast = astCreateFcc(tka) }
	case 304, 311:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_ARG_LIST, yyvsa[yyvsp].ast) }
	case 308:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_ARG_LIST, yyvsa[yyvsp-2].ast) }
	case 310:
		{ yyval.ast = astCreateList2(tka, ZEND_AST_ARG_LIST, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 313:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NAMED_ARG, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 314, 607:
		{ yyval.ast = astCreate1(tka, ZEND_AST_UNPACK, yyvsa[yyvsp].ast) }
	case 319:
		{ yyval.ast = astCreate1(tka, ZEND_AST_GLOBAL, astCreate1(tka, ZEND_AST_VAR, yyvsa[yyvsp].ast)) }
	case 322:
		{ yyval.ast = astCreate2(tka, ZEND_AST_STATIC, yyvsa[yyvsp].ast, nil) }
	case 323:
		{ yyval.ast = astCreate2(tka, ZEND_AST_STATIC, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 326:
		{ yyval.ast = astCreate3(tka, ZEND_AST_PROP_GROUP, yyvsa[yyvsp-2].ast, yyvsa[yyvsp-1].ast, nil); yyval.ast.Attr = AstAttr(yyvsa[yyvsp].num) }
	case 327:
		{ yyval.ast = astCreate3(tka, ZEND_AST_PROP_GROUP, yyvsa[yyvsp-1].ast, astCreateList1(tka, ZEND_AST_PROP_DECL, yyvsa[yyvsp].ast), nil); yyval.ast.Attr = AstAttr(yyvsa[yyvsp].num) }
	case 328:
		{ yyval.ast = astCreate3(tka, ZEND_AST_CLASS_CONST_GROUP, yyvsa[yyvsp-1].ast, nil, nil); yyval.ast.Attr = AstAttr(yyvsa[yyvsp].num) }
	case 329:
		{ yyval.ast = astCreate3(tka, ZEND_AST_CLASS_CONST_GROUP, yyvsa[yyvsp-1].ast, nil, yyvsa[yyvsp-2].ast); yyval.ast.Attr = AstAttr(yyvsa[yyvsp].num) }
	case 330:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_METHOD, uint32(yyvsa[yyvsp-9].num|yyvsa[yyvsp-11].num|yyvsa[yyvsp].num), yyvsa[yyvsp-10].tka, p.getTknStr(yyvsa[yyvsp-7].tka), p.getTknStr(yyvsa[yyvsp-8].tka), yyvsa[yyvsp-5].ast, nil, yyvsa[yyvsp-1].ast, yyvsa[yyvsp-3].ast, nil); p.extraFnFlags = yyvsa[yyvsp-2].num }
	case 334:
		{ yyval.ast = astCreate2(tka, ZEND_AST_USE_TRAIT, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 340:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_TRAIT_ADAPTATIONS, yyvsa[yyvsp].ast) }
	case 344:
		{ yyval.ast = astCreate2(tka, ZEND_AST_TRAIT_PRECEDENCE, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 345:
		{ yyval.ast = astCreate2(tka, ZEND_AST_TRAIT_ALIAS, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 346:
		{ zast, errLexT := p.lexTString(yyvsa[yyvsp].tka); if errLexT != nil { err = errLexT; goto yyabortlab }; yyval.ast = astCreate2(tka, ZEND_AST_TRAIT_ALIAS, yyvsa[yyvsp-2].ast, zast) }
	case 347:
		{ modifiers, err = p.modifierTokenToFlag(yyvsa[yyvsp-1].tka, ZEND_MODIFIER_TARGET_METHOD); yyval.ast = astCreateEx2(tka, ZEND_AST_TRAIT_ALIAS, modifiers, yyvsa[yyvsp-3].ast, yyvsa[yyvsp].ast); /* identifier nonterminal can cause allocations, so we need to free the node */ if modifiers == 0 { goto yyerrorlab } }
	case 348:
		{ modifiers, err = p.modifierTokenToFlag(yyvsa[yyvsp].tka, ZEND_MODIFIER_TARGET_METHOD); yyval.ast = astCreateEx2(tka, ZEND_AST_TRAIT_ALIAS, modifiers, yyvsa[yyvsp-2].ast, nil); /* identifier nonterminal can cause allocations, so we need to free the node */ if modifiers == 0 { goto yyerrorlab } }
	case 349:
		{ yyval.ast = astCreate2(tka, ZEND_AST_METHOD_REFERENCE, nil, yyvsa[yyvsp].ast) }
	case 351:
		{ yyval.ast = astCreate2(tka, ZEND_AST_METHOD_REFERENCE, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 354:
		{ yyval.num, err = p.modifierListToFlags(tka, ZEND_MODIFIER_TARGET_PROPERTY, yyvsa[yyvsp].ast); if yyval.num == 0 { goto yyerrorlab } }
	case 355, 356, 358:
		{ yyval.num = ZEND_ACC_PUBLIC }
	case 357:
		{ yyval.num, err = p.modifierListToFlags(tka, ZEND_MODIFIER_TARGET_METHOD, yyvsa[yyvsp].ast); if yyval.num == 0 { goto yyerrorlab }; if yyval.num & ZEND_ACC_PPP_MASK == 0 { yyval.num |= ZEND_ACC_PUBLIC } }
	case 359:
		{ yyval.num, err = p.modifierListToFlags(tka, ZEND_MODIFIER_TARGET_CONSTANT, yyvsa[yyvsp].ast); if yyval.num == 0 { goto yyerrorlab }; if yyval.num & ZEND_ACC_PPP_MASK == 0 { yyval.num |= ZEND_ACC_PUBLIC } }
	case 360:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_MODIFIER_LIST, p.astCreateZvalFromLong(tka, yyvsa[yyvsp].num)) }
	case 361:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-1].ast, p.astCreateZvalFromLong(tka, yyvsa[yyvsp].num)) }
	case 362:
		{ yyval.num = int(T_PUBLIC) }
	case 363:
		{ yyval.num = int(T_PROTECTED) }
	case 364:
		{ yyval.num = int(T_PRIVATE) }
	case 365:
		{ yyval.num = int(T_PUBLIC_SET) }
	case 366:
		{ yyval.num = int(T_PROTECTED_SET) }
	case 367:
		{ yyval.num = int(T_PRIVATE_SET) }
	case 368:
		{ yyval.num = int(T_STATIC) }
	case 369:
		{ yyval.num = int(T_ABSTRACT) }
	case 370:
		{ yyval.num = int(T_FINAL) }
	case 371:
		{ yyval.num = int(T_READONLY) }
	case 373:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_PROP_DECL, yyvsa[yyvsp].ast) }
	case 374:
		{ yyval.ast = astCreate4(tka, ZEND_AST_PROP_ELEM, yyvsa[yyvsp-1].ast, nil, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp].tka)), nil) }
	case 375:
		{ yyval.ast = astCreate4(tka, ZEND_AST_PROP_ELEM, yyvsa[yyvsp-3].ast, yyvsa[yyvsp-1].ast, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp].tka)), nil) }
	case 376:
		{ yyval.ast = astCreate4(tka, ZEND_AST_PROP_ELEM, yyvsa[yyvsp-4].ast, nil, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp-3].tka)), yyvsa[yyvsp-1].ast) }
	case 377:
		{ yyval.ast = astCreate4(tka, ZEND_AST_PROP_ELEM, yyvsa[yyvsp-6].ast, yyvsa[yyvsp-4].ast, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp-3].tka)), yyvsa[yyvsp-1].ast) }
	case 380:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-2].ast, astWithAttributes(yyvsa[yyvsp].ast, yyvsa[yyvsp-1].ast)) }
	case 384:
		{ yyval.num, err = p.modifierListToFlags(tka, ZEND_MODIFIER_TARGET_PROPERTY_HOOK, yyvsa[yyvsp].ast); if yyval.num == 0 { goto yyerrorlab } }
	case 386:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_PROPERTY_HOOK, uint32(yyvsa[yyvsp-8].num|yyvsa[yyvsp-7].num|yyvsa[yyvsp].num), yyvsa[yyvsp-4].tka, p.getTknStr(yyvsa[yyvsp-5].tka), p.getTknStr(yyvsa[yyvsp-6].tka), yyvsa[yyvsp-3].ast, nil, yyvsa[yyvsp-1].ast, nil, nil); p.extraFnFlags = yyvsa[yyvsp-2].num }
	case 389:
		{ yyval.ast = astCreate1(tka, ZEND_AST_PROPERTY_HOOK_SHORT_BODY, yyvsa[yyvsp-1].ast) }
	case 393:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_CLASS_CONST_DECL, yyvsa[yyvsp].ast) }
	case 394, 396:
		{ yyval.ast = astCreate3(tka, ZEND_AST_CONST_ELEM, yyvsa[yyvsp-3].ast, yyvsa[yyvsp-1].ast, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp].tka))) }
	case 395:
		{ zast, errLexT := p.lexTString(yyvsa[yyvsp-3].tka); if errLexT != nil { err = errLexT; goto yyabortlab }; yyval.ast = astCreate3(tka, ZEND_AST_CONST_ELEM, zast, yyvsa[yyvsp-1].ast, astCreateZvalStrOrNil(tka, p.getAstTknVal(yyvsa[yyvsp].tka))) }
	case 406:
		{ yyval.ast = astListAdd(yyvsa[yyvsp-3].ast, astCreate1(tka, ZEND_AST_CAST_VOID, yyvsa[yyvsp].ast)) }
	case 407:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_EXPR_LIST, astCreate1(tka, ZEND_AST_CAST_VOID, yyvsa[yyvsp].ast)) }
	case 410:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NEW, astCreateDecl(tka, ZEND_AST_CLASS, ZEND_ACC_ANON_CLASS | uint32(yyvsa[yyvsp-9].num), yyvsa[yyvsp-7].tka, p.getTknStr(yyvsa[yyvsp-3].tka), "", yyvsa[yyvsp-5].ast, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast, nil, nil), yyvsa[yyvsp-6].ast) }
	case 411:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NEW, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 414:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NEW, yyvsa[yyvsp].ast, astCreateList0(tka, ZEND_AST_ARG_LIST)) }
	case 416, 417:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ASSIGN, yyvsa[yyvsp-3].ast, yyvsa[yyvsp].ast) }
	case 418:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ASSIGN, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 419:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ASSIGN_REF, yyvsa[yyvsp-3].ast, yyvsa[yyvsp].ast) }
	case 420:
		{ yyval.ast = astCreate2(tka, ZEND_AST_CALL, p.astCreateZvalStrAttr(tka, ZEND_STR_CLONE, ZEND_NAME_FQ), yyvsa[yyvsp].ast) }
	case 421:
		{ yyval.ast = astCreate2(tka, ZEND_AST_CALL, p.astCreateZvalStrAttr(tka, ZEND_STR_CLONE, ZEND_NAME_FQ), astCreateList1(tka, ZEND_AST_ARG_LIST, yyvsa[yyvsp].ast)) }
	case 422:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_ADD, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 423:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_SUB, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 424:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_MUL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 425:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_POW, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 426:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_DIV, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 427:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_CONCAT, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 428:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_MOD, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 429:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_BW_AND, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 430:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_BW_OR, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 431:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_BW_XOR, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 432:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_SL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 433:
		{ yyval.ast = astCreateAssignOp(tka, ZEND_SR, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 434:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ASSIGN_COALESCE, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 435:
		{ yyval.ast = astCreate1(tka, ZEND_AST_POST_INC, yyvsa[yyvsp-1].ast) }
	case 436:
		{ yyval.ast = astCreate1(tka, ZEND_AST_PRE_INC, yyvsa[yyvsp].ast) }
	case 437:
		{ yyval.ast = astCreate1(tka, ZEND_AST_POST_DEC, yyvsa[yyvsp-1].ast) }
	case 438:
		{ yyval.ast = astCreate1(tka, ZEND_AST_PRE_DEC, yyvsa[yyvsp].ast) }
	case 439, 441:
		{ yyval.ast = astCreate2(tka, ZEND_AST_OR, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 440, 442, 634:
		{ yyval.ast = astCreate2(tka, ZEND_AST_AND, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 443:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_BOOL_XOR, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 444:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_BW_OR, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 445, 446:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_BW_AND, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 447:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_BW_XOR, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 448:
		{ yyval.ast = astCreateConcatOp(tka, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 449:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_ADD, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 450:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_SUB, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 451:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_MUL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 452:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_POW, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 453:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_DIV, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 454:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_MOD, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 455:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_SL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 456:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_SR, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 457:
		{ yyval.ast = astCreate1(tka, ZEND_AST_UNARY_PLUS, yyvsa[yyvsp].ast) }
	case 458:
		{ yyval.ast = astCreate1(tka, ZEND_AST_UNARY_MINUS, yyvsa[yyvsp].ast) }
	case 459:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_UNARY_OP, ZEND_BOOL_NOT, yyvsa[yyvsp].ast) }
	case 460:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_UNARY_OP, ZEND_BW_NOT, yyvsa[yyvsp].ast) }
	case 461:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_IS_IDENTICAL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 462:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_IS_NOT_IDENTICAL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 463:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_IS_EQUAL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 464:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_IS_NOT_EQUAL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 465:
		{ yyval.ast = astCreate2(tka, ZEND_AST_PIPE, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 466:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_IS_SMALLER, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 467:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_IS_SMALLER_OR_EQUAL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 468:
		{ yyval.ast = astCreate2(tka, ZEND_AST_GREATER, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 469:
		{ yyval.ast = astCreate2(tka, ZEND_AST_GREATER_EQUAL, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 470:
		{ yyval.ast = astCreateBinaryOp(tka, ZEND_SPACESHIP, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 471:
		{ yyval.ast = astCreate2(tka, ZEND_AST_INSTANCEOF, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 472:
		{ yyval.ast = yyvsa[yyvsp-1].ast; if yyval.ast.Kind == ZEND_AST_CONDITIONAL { yyval.ast.Attr = ZEND_PARENTHESIZED_CONDITIONAL }; if yyval.ast.Kind == ZEND_AST_ARROW_FUNC { yyval.ast.Attr = ZEND_PARENTHESIZED_ARROW_FUNC } }
	case 475:
		{ yyval.ast = astCreate3(tka, ZEND_AST_CONDITIONAL, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 476:
		{ yyval.ast = astCreate3(tka, ZEND_AST_CONDITIONAL, yyvsa[yyvsp-3].ast, nil, yyvsa[yyvsp].ast) }
	case 477:
		{ yyval.ast = astCreate2(tka, ZEND_AST_COALESCE, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 479:
		{ yyval.ast = astCreateCast(tka, IS_LONG, yyvsa[yyvsp].ast) }
	case 480:
		{ yyval.ast = astCreateCast(tka, IS_DOUBLE, yyvsa[yyvsp].ast) }
	case 481:
		{ yyval.ast = astCreateCast(tka, IS_STRING, yyvsa[yyvsp].ast) }
	case 482:
		{ yyval.ast = astCreateCast(tka, IS_ARRAY, yyvsa[yyvsp].ast) }
	case 483:
		{ yyval.ast = astCreateCast(tka, IS_OBJECT, yyvsa[yyvsp].ast) }
	case 484:
		{ yyval.ast = astCreateCast(tka, _IS_BOOL, yyvsa[yyvsp].ast) }
	case 485:
		{ yyval.ast = astCreateCast(tka, IS_NULL, yyvsa[yyvsp].ast) }
	case 486:
		{ yyval.ast = astCreate2(tka, ZEND_AST_CALL, p.astCreateZvalStrAttr(tka, ZEND_STR_EXIT, ZEND_NAME_FQ), yyvsa[yyvsp].ast) }
	case 487:
		{ yyval.ast = astCreate1(tka, ZEND_AST_SILENCE, yyvsa[yyvsp].ast) }
	case 489:
		{ yyval.ast = astCreate1(tka, ZEND_AST_SHELL_EXEC, yyvsa[yyvsp-1].ast) }
	case 490:
		{ yyval.ast = astCreate1(tka, ZEND_AST_PRINT, yyvsa[yyvsp].ast) }
	case 491:
		{ yyval.ast = astCreate2(tka, ZEND_AST_YIELD, nil, nil); p.extraFnFlags |= ZEND_ACC_GENERATOR }
	case 492:
		{ yyval.ast = astCreate2(tka, ZEND_AST_YIELD, yyvsa[yyvsp].ast, nil); p.extraFnFlags |= ZEND_ACC_GENERATOR }
	case 493:
		{ yyval.ast = astCreate2(tka, ZEND_AST_YIELD, yyvsa[yyvsp].ast, yyvsa[yyvsp-2].ast); p.extraFnFlags |= ZEND_ACC_GENERATOR }
	case 494:
		{ yyval.ast = astCreate1(tka, ZEND_AST_YIELD_FROM, yyvsa[yyvsp].ast); p.extraFnFlags |= ZEND_ACC_GENERATOR }
	case 495:
		{ yyval.ast = astCreate1(tka, ZEND_AST_THROW, yyvsa[yyvsp].ast) }
	case 498:
		{ yyval.ast = yyvsa[yyvsp].ast; (*AstDecl)(unsafe.Pointer(yyval.ast)).Flags |= ZEND_ACC_STATIC }
	case 499:
		{ yyval.ast = astWithAttributes(yyvsa[yyvsp].ast, yyvsa[yyvsp-2].ast); (*AstDecl)(unsafe.Pointer(yyval.ast)).Flags |= ZEND_ACC_STATIC }
	case 501:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_CLOSURE, uint32(yyvsa[yyvsp-11].num|yyvsa[yyvsp].num), yyvsa[yyvsp-12].tka, p.getTknStr(yyvsa[yyvsp-10].tka), "", yyvsa[yyvsp-8].ast, yyvsa[yyvsp-6].ast, yyvsa[yyvsp-2].ast, yyvsa[yyvsp-5].ast, nil); p.extraFnFlags = yyvsa[yyvsp-4].num }
	case 502:
		{ yyval.ast = astCreateDecl(tka, ZEND_AST_ARROW_FUNC, uint32(yyvsa[yyvsp-10].num|yyvsa[yyvsp].num), yyvsa[yyvsp-11].tka, p.getTknStr(yyvsa[yyvsp-9].tka), "", yyvsa[yyvsp-7].ast, nil, yyvsa[yyvsp-1].ast, yyvsa[yyvsp-5].ast, nil); p.extraFnFlags = yyvsa[yyvsp-3].num }
	case 505:
		{ yyval.tka = AstTkn(p.lexer.docComment - p.tknOffset); p.lexer.docComment = 0; }
	case 506:
		{ yyval.num = p.extraFnFlags; p.extraFnFlags = 0 }
	case 507:
		{ /* yyval.ptr = p.cursor */ }
	case 509:
		{ yyval.num = ZEND_ACC_RETURN_REFERENCE }
	case 513:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_CLOSURE_USES, yyvsa[yyvsp].ast) }
	case 515:
		{ yyval.ast = yyvsa[yyvsp].ast; yyval.ast.Attr = ZEND_BIND_REF }
	case 516:
		{ yyval.ast = astCreate2(tka, ZEND_AST_CALL, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 517:
		{ zast, errLexT := p.lexTString(yyvsa[yyvsp-1].tka); if errLexT != nil { err = errLexT; goto yyabortlab }; yyval.ast = astCreate2(tka, ZEND_AST_CALL, zast, yyvsa[yyvsp].ast) }
	case 518, 519:
		{ yyval.ast = astCreate3(tka, ZEND_AST_STATIC_CALL, yyvsa[yyvsp-3].ast, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 522:
		{ zv := p.newTknValStr(tka, ZEND_STR_STATIC); yyval.ast = astCreateZvalEx(tka, zv, ZEND_NAME_NOT_FQ) }
	case 527, 539:
		{ yyval.ast = p.astCreateZvalFromStr(tka, "") }
	case 532:
		{ yyval.ast = yyvsa[yyvsp-1].ast; yyval.ast.Attr = ZEND_ARRAY_SYNTAX_LONG }
	case 544:
		{ yyval.ast = astCreate1(tka, ZEND_AST_CONST, yyvsa[yyvsp].ast) }
	case 545:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_LINE)) }
	case 546:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_FILE)) }
	case 547:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_DIR)) }
	case 548:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_TRAIT_C)) }
	case 549:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_METHOD_C)) }
	case 550:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_FUNC_C)) }
	case 551:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_PROPERTY_C)) }
	case 552:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_NS_C)) }
	case 553:
		{ yyval.ast = astCreateEx0(tka, ZEND_AST_MAGIC_CONST, AstAttr(T_CLASS_C)) }
	case 554, 555:
		{ yyval.ast = astCreateClassConstOrName(tka, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast, p.getTknStr(yyvsa[yyvsp].tka)) }
	case 556, 557:
		{ yyval.ast = astCreate2(tka, ZEND_AST_CLASS_CONST, yyvsa[yyvsp-4].ast, yyvsa[yyvsp-1].ast) }
	case 562:
		{ yyval.ast = yyvsa[yyvsp-1].ast; if yyval.ast.Kind == ZEND_AST_STATIC_PROP { yyval.ast.Attr = ZEND_PARENTHESIZED_STATIC_PROP } }
	case 572, 583, 586, 594, 597, 614, 625:
		{ yyval.ast = astCreate1(tka, ZEND_AST_VAR, yyvsa[yyvsp].ast) }
	case 573, 587:
		{ yyval.ast = astCreate2(tka, ZEND_AST_DIM, yyvsa[yyvsp-3].ast, yyvsa[yyvsp-1].ast) }
	case 574:
		{ yyval.ast = astCreate3(tka, ZEND_AST_METHOD_CALL, yyvsa[yyvsp-3].ast, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 575:
		{ yyval.ast = astCreate3(tka, ZEND_AST_NULLSAFE_METHOD_CALL, yyvsa[yyvsp-3].ast, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 579, 588:
		{ yyval.ast = astCreate2(tka, ZEND_AST_PROP, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 580, 589:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NULLSAFE_PROP, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 584, 585, 590, 591:
		{ yyval.ast = astCreate2(tka, ZEND_AST_STATIC_PROP, yyvsa[yyvsp-2].ast, yyvsa[yyvsp].ast) }
	case 598:
		{ /* allow single trailing comma */ yyval.ast = astListRtrim(yyvsa[yyvsp].ast) }
	case 602:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_ARRAY, yyvsa[yyvsp].ast) }
	case 603:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ARRAY_ELEM, yyvsa[yyvsp].ast, yyvsa[yyvsp-2].ast) }
	case 604:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ARRAY_ELEM, yyvsa[yyvsp].ast, nil) }
	case 605:
		{ yyval.ast = astCreateEx2(tka, ZEND_AST_ARRAY_ELEM, 1, yyvsa[yyvsp].ast, yyvsa[yyvsp-3].ast) }
	case 606:
		{ yyval.ast = astCreateEx2(tka, ZEND_AST_ARRAY_ELEM, 1, yyvsa[yyvsp].ast, nil) }
	case 608:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ARRAY_ELEM, yyvsa[yyvsp-1].ast, yyvsa[yyvsp-5].ast) }
	case 609:
		{ yyval.ast = astCreate2(tka, ZEND_AST_ARRAY_ELEM, yyvsa[yyvsp-1].ast, nil) }
	case 612:
		{ yyval.ast = astCreateList1(tka, ZEND_AST_ENCAPS_LIST, yyvsa[yyvsp].ast) }
	case 613:
		{ yyval.ast = astCreateList2(tka, ZEND_AST_ENCAPS_LIST, yyvsa[yyvsp-1].ast, yyvsa[yyvsp].ast) }
	case 615:
		{ yyval.ast = astCreate2(tka, ZEND_AST_DIM, astCreate1(tka, ZEND_AST_VAR, yyvsa[yyvsp-3].ast), yyvsa[yyvsp-1].ast) }
	case 616:
		{ yyval.ast = astCreate2(tka, ZEND_AST_PROP, astCreate1(tka, ZEND_AST_VAR, yyvsa[yyvsp-2].ast), yyvsa[yyvsp].ast) }
	case 617:
		{ yyval.ast = astCreate2(tka, ZEND_AST_NULLSAFE_PROP, astCreate1(tka, ZEND_AST_VAR, yyvsa[yyvsp-2].ast), yyvsa[yyvsp].ast) }
	case 618:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_VAR, ZEND_ENCAPS_VAR_DOLLAR_CURLY_VAR_VAR, yyvsa[yyvsp-1].ast) }
	case 619:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_VAR, ZEND_ENCAPS_VAR_DOLLAR_CURLY, yyvsa[yyvsp-1].ast) }
	case 620:
		{ yyval.ast = astCreateEx2(tka, ZEND_AST_DIM, ZEND_ENCAPS_VAR_DOLLAR_CURLY, astCreate1(tka, ZEND_AST_VAR, yyvsa[yyvsp-4].ast), yyvsa[yyvsp-2].ast) }
	case 624:
		{ yyval.ast = negateNumString(yyvsa[yyvsp].ast) }
	case 627:
		{ yyval.ast = astCreate1(tka, ZEND_AST_EMPTY, yyvsa[yyvsp-1].ast) }
	case 628:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_INCLUDE_OR_EVAL, ZEND_INCLUDE, yyvsa[yyvsp].ast) }
	case 629:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_INCLUDE_OR_EVAL, ZEND_INCLUDE_ONCE, yyvsa[yyvsp].ast) }
	case 630:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_INCLUDE_OR_EVAL, ZEND_EVAL, yyvsa[yyvsp-1].ast) }
	case 631:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_INCLUDE_OR_EVAL, ZEND_REQUIRE, yyvsa[yyvsp].ast) }
	case 632:
		{ yyval.ast = astCreateEx1(tka, ZEND_AST_INCLUDE_OR_EVAL, ZEND_REQUIRE_ONCE, yyvsa[yyvsp].ast) }
	case 635:
		{ yyval.ast = astCreate1(tka, ZEND_AST_ISSET, yyvsa[yyvsp].ast) }
	}


	// YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);
	yyvsp -= yylen
	yyssp -= yylen
	yylen = 0

	// YY_STACK_PRINT (yyss, yyssp);

	yyvsp += 1
	yyvsa[yyvsp] = yyval

	yyn = int(yyr1[yyn])
	yystate = int(yypgoto[yyn-YYNTOKENS]) + yyssa[yyssp]
	if 0 <= yystate && yystate <= YYLAST && int(yycheck[yystate]) == yyssa[yyssp] {
		yystate = int(yytable[yystate])
	} else {
		yystate = int(yydefgoto[yyn-YYNTOKENS])
	}

	goto yynewstate

yyerrlab:
	yytoken = YYEMPTY
	if yychar != YYEMPTY {
		yytoken = YYUNDEFTOK
		if uint(yychar) <= YYMAXUTOK {
			yytoken = int(yytranslate[yychar])
		}
	}
	/* If not already recovering from an error, report this error.  */
	if yyerrstatus == 0 {
		yynerrs += 1
		err = p.yySyntaxError(tka, "syntax error", yyssa, yyssp, yytoken)
	}

	if yyerrstatus == 3 {
		/* If just tried and failed to reuse lookahead token after an error, discard it.  */
		if yychar <= YYEOF {
			/* Return failure if at end of input.  */
			if yychar == YYEOF {
				goto yyabortlab
			}
		} else {
			// yydestruct ("Error: discarding", yytoken, &yylval);
			yychar = YYEMPTY
		}
	}
	goto yyerrlab1

yyerrorlab:
	//goland:noinspection GoUnreachableCode
	{
		if false {
			goto yyerrorlab
		}

		/* Do not reclaim the symbols of the rule whose action triggered this YYERROR.  */

		yyvsp -= yylen
		yyssp -= yylen
		yylen = 0

		// YY_STACK_PRINT (yyss, yyssp);

		yystate = yyssa[yyssp]
	}

yyerrlab1:
	/* Else will try to reuse lookahead token after shifting the error token.  */
	yyerrstatus = 3
	for {
		yyn = int(yypact[yystate])
		if !(yyn == YYPACT_NINF) {
			yyn += 1
			if 0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR {
				yyn = int(yytable[yyn])
				if 0 < yyn {
					break
				}
			}
		}

		/* Pop the current state because it cannot handle the error token.  */
		if yyssp == 0 {
			goto yyabortlab
		}

		// yydestruct ("Error: popping", YY_ACCESSING_SYMBOL (yystate), yyvsp);
		yyvsp -= 1
		yyssp -= 1
		yystate = yyssa[yyssp]
		// YY_STACK_PRINT (yyss, yyssp);
	}

	yyvsp += 1
	yyvsa[yyvsp] = yylval

	/* Shift the error token.  */
	// YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);

	yystate = yyn
	goto yynewstate

yyacceptlab:
	return 0, nil

yyabortlab:
	/* clean up and return
	if yychar != YYEMPTY {
		// Make sure we have latest lookahead translation.  See comments at
		// user semantic actions for why this is necessary.
		yytoken = YYUNDEFTOK
		if uint(yychar) <= YYMAXUTOK {
			yytoken = int(yytranslate[yychar])
		}
		// yydestruct ("Cleanup: discarding lookahead", yytoken, &yylval);
	}
	// Do not reclaim the symbols of the rule whose action triggered this YYABORT or YYACCEPT
	yyvsp -= yylen
	yyssp -= yylen
	// YY_STACK_PRINT (yyss, yyssp);
	for yyssp > 0 {
		// yydestruct ("Cleanup: popping", YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
		yyvsp -= 1
		yyssp -= 1
	} */

	return 1, err
}

